

very_sensitive_combinations = [
    ["[*]"],
    ["acm:ExportCertificate"],
    ["aps:PutResourcePolicy"],
    ["athena:CreatePresignedNotebookUrl"],
    ["athena:StartCalculationExecution"],
    ["iam:PassRole"],

    ["backup:PutBackupVaultAccessPolicy"],

    ["servicecatalog:CreateProvisioningArtifact", "servicecatalog:ProvisionProduct"],

    ["imagebuilder:CreateComponent", "imagebuilder:StartImagePipelineExecution"],

    [
        "codedeploy:CreateDeployment",
        "codedeploy:GetDeploymentConfig",
        "codedeploy:RegisterApplicationRevision",
    ],

    ["codebuild:StartBuild"],
    ["codebuild:StartBuildBatch"],
    ["codebuild:StartCommandExecution"],

    [
        "synthetics:StartCanaryDryRun",
        "lambda:GetFunctionConfiguration",
        "lambda:PublishLayerVersion",
        "lambda:GetLayerVersion",
        "lambda:UpdateFunctionConfiguration",
        "lambda:PublishVersion",
        "lambda:AddPermission",
        "iam:PassRole",
    ],

    ["cognito-identity:UpdateIdentityPool"],
    ["cognito-idp:AdminAddUserToGroup"],
    ["cognito-idp:AdminConfirmSignUp"],
    ["cognito-idp:AdminCreateUser"],
    ["cognito-idp:AdminSetUserPassword"],
    ["cognito-idp:SetUserPoolMfaConfig"],
    ["cognito-idp:UpdateUserPool"],
    ["cognito-idp:AdminUpdateUserAttributes"],
    ["cognito-idp:CreateUserPoolClient"],
    ["cognito-idp:UpdateUserPoolClient"],
    ["cognito-idp:CreateUserImportJob"],
    ["cognito-idp:StartUserImportJob"],
    ["cognito-idp:CreateIdentityProvider"],
    ["cognito-idp:UpdateIdentityProvider"],

    ["ds:ResetUserPassword"],

    ["docdb-elastic:UpdateCluster"],

    ["dsql:PutClusterPolicy"],

    ["dynamodb:PutResourcePolicy"],

    ["entityresolution:PutPolicy"],

    ["glue:RunStatement"],

    ["ec2:ModifyInstanceAttribute"],
    ["eks:CreateAccessEntry", "eks:AssociateAccessPolicy"],
    ["eks-auth:AssumeRoleForPodIdentity"],
    ["es:UpdateDomainConfig"],
    ["ec2:CreateLaunchTemplateVersion", "ec2:CreateLaunchTemplate", "ec2:ModifyLaunchTemplate"],
    ["ec2-instance-connect:SendSSHPublicKey"],

    ["ebs:ListSnapshotBlocks", "ebs:GetSnapshotBlock"],

    ["ecr:GetAuthorizationToken", "ecr:BatchCheckLayerAvailability", "ecr:CompleteLayerUpload", "ecr:InitiateLayerUpload", "ecr:PutImage", "ecr:UploadLayerPart"],
    ["ecr-public:GetAuthorizationToken", "ecr-public:BatchCheckLayerAvailability", "ecr-public:CompleteLayerUpload", "ecr-public:InitiateLayerUpload", "ecr-public:PutImage", "ecr-public:UploadLayerPart"],
    ["ecr:SetRepositoryPolicy"],
    ["ecr-public:SetRepositoryPolicy"],
    ["ecr:PutRegistryPolicy"],

    ["ecs:RegisterTaskDefinition"],
    ["ecs:ExecuteCommand"],

    ["events:PutTargets", "events:PutEvents"],

    ["fis:UpdateExperimentTemplate", "fis:StartExperiment"],

    ["elasticfilesystem:DeleteFileSystemPolicy"],
    ["elasticfilesystem:PutFileSystemPolicy"],

    ["gamelift:GetComputeAccess"],
    ["gameliftstreams:CreateStreamSessionAdminShell"],

    ["grafana:CreateWorkspaceApiKey"],
    ["grafana:CreateWorkspaceServiceAccountToken"],

    ["glue:UpdateDevEndpoint"],
    ["glue:UpdateJob"],

    ["iam:CreatePolicyVersion"],
    ["iam:SetDefaultPolicyVersion"],
    ["iam:CreateAccessKey"],
    ["iam:CreateLoginProfile"],
    ["iam:UpdateLoginProfile"],
    ["iam:UpdateAccessKey"],
    ["iam:CreateServiceSpecificCredential"],
    ["iam:ResetServiceSpecificCredential"],
    ["iam:AttachUserPolicy"],
    ["iam:AttachGroupPolicy"],
    ["iam:AttachRolePolicy"],
    ["iam:PutUserPolicy"],
    ["iam:PutGroupPolicy"],
    ["iam:PutRolePolicy"],
    ["iam:AddUserToGroup"],
    ["iam:UpdateAssumeRolePolicy"],
    ["iam:UploadSSHPublicKey"],
    ["iam:DeactivateMFADevice"],
    ["iam:ResyncMFADevice"],
    ["iam:UpdateSAMLProvider"],
    ["iam:UpdateOpenIDConnectProviderThumbprint"],

    ["iot:OpenTunnel"],

    ["kms:PutKeyPolicy"],
    ["kms:CreateGrant"],

    ["lambda:AddPermission"],
    ["lambda:AddLayerVersionPermission"],
    ["lambda:UpdateFunctionCode"],

    ["lightsail:DownloadDefaultKeyPair"],
    ["lightsail:GetInstanceAccessDetails"],
    ["lightsail:CreateBucketAccessKey"],
    ["lightsail:GetRelationalDatabaseMasterUserPassword"],
    ["lightsail:UpdateRelationalDatabase"],
    ["lightsail:UpdateBucket"],
    ["lightsail:UpdateDomainEntry"],
    ["lightsail:CreateDomainEntry"],

    ["kafka:UpdateSecurity"],

    ["rds:ModifyDBInstance"],

    ["redshift:GetClusterCredentials"],
    ["redshift:GetClusterCredentialsWithIAM"],

    ["route53:CreateHostedZone", "route53:ChangeResourceRecordSets", "acm-pca:IssueCertificate",  "acm-pca:GetCertificate"],

    ["rolesanywhere:UpdateTrustAnchor"],

    ["sns:AddPermission"],
    ["sns:SetTopicAttributes"],

    ["sqs:AddPermission"],
    ["sqs:SetQueueAttributes"],

    ["identitystore:CreateGroupMembership"],
    ["sso:PutInlinePolicyToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:AttachManagedPolicyToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:AttachCustomerManagedPolicyReferenceToPermissionSet", "sso:ProvisionPermissionSet"],
    ["sso:CreateAccountAssignment"],

    ["s3:PutBucketPolicy"],
    ["s3:PutBucketAcl"],
    ["s3:PutAccessPointPolicy"],
    ["s3:PutObjectAcl"],
    ["s3:PutObjectVersionAcl"],
    ["s3tables:PutTableBucketPolicy"],
    ["s3tables:PutTablePolicy"],

    ["sagemaker:CreatePresignedNotebookInstanceUrl"],
    ["sagemaker:UpdateNotebookInstanceLifecycleConfig"],

    ["secretsmanager:GetSecretValue"],
    ["secretsmanager:PutResourcePolicy"],

    ["ssm:SendCommand"],
    ["ssm:StartAutomationExecution"],
    ["ssm:StartSession"],
    ["ssm:ResumeSession"],

    ["states:UpdateStateMachine"],

    ["sts:AssumeRole"],
    ["sts:AssumeRoleWithSAML"],
    ["sts:AssumeRoleWithWebIdentity"],
    ["codeartifact:GetAuthorizationToken", "sts:GetServiceBearerToken"],
    [
        "bedrock-agentcore:GetWorkloadAccessTokenForUserId",
        "bedrock-agentcore:GetResourceApiKey",
        "secretsmanager:GetSecretValue",
    ],
]

sensitive_combinations = [
    ["mq:CreateUser"],
    ["mq:UpdateUser"],
    ["account:GetContactInformation"],
    ["amplify:GetApp", "amplifybackend:CreateToken"],
    ["amplify:GetApp", "amplifybackend:GetToken"],
    ["amplify:GetApp"],
    ["amplify:GetArtifactUrl"],
    ["amplify:GetJob"],
    ["appconfig:GetHostedConfigurationVersion"],
    ["appconfig:StartConfigurationSession", "appconfig:GetLatestConfiguration"],
    ["appsync:GraphQL"],
    ["appsync:ListApiKeys"],
    ["appstream:CreateStreamingURL"],
    ["cassandra:Select"],
    ["cassandra:Modify", "cassandra:Select"],
    ["dax:BatchGetItem"],
    ["dax:GetItem"],
    ["dax:Query"],
    ["dax:Scan"],
    ["devicefarm:GetRemoteAccessSession"],
    ["devicefarm:ListArtifacts"],
    ["dsql:DbConnect"],
    ["dsql:DbConnectAdmin"],
    ["ec2-instance-connect:OpenTunnel"],
    ["ec2-instance-connect:SendSerialConsoleSSHPublicKey"],
    ["elemental-inference:ExportDictionaryEntries"],
    ["elemental-inference:GetMetadata"],
    ["athena:GetQueryExecution"],
    ["autoscaling:DescribeLaunchConfigurations"],
    ["backup:DeleteRecoveryPoint"],
    ["backup:StartRestoreJob", "iam:PassRole"],
    [
        "backup:CreateBackupAccessPoint",
        "backup:DescribeBackupAccessPoint",
        "s3:CreateAccessPoint",
        "s3:GetAccessPoint",
        "s3:PutAccessPointPolicy",
    ],
    ["batch:DescribeJobDefinitions"],
    ["bedrock:Retrieve"],
    ["bedrock-agentcore:GetWorkloadAccessTokenForUserId"],
    ["b2bi:GetProfile"],
    ["b2bi:GetTransformer"],
    ["cloudfront:GetFunction"],
    ["cloudformation:DescribeStacks"],
    ["cloudformation:DescribeChangeSet"],
    ["cloudformation:GetTemplate"],
    ["cloudformation:GetTemplateSummary"],
    ["cloudformation:ListExports"],
    ["cloudtrail:LookupEvents"],
    ["ce:GetCostAndUsage"],
    ["budgets:ViewBudget"],
    ["aws-portal:ViewBilling"],
    ["aws-marketplace:SearchAgreements"],
    ["aws-marketplace:DescribeAgreement"],
    ["aws-marketplace:GetAgreementTerms"],
    ["cloudfront:GetDistribution"],
    ["cloudfront:GetDistributionConfig"],
    ["cloudfront:ListDistributions"],
    ["cloudwatch:GetDashboard"],
    ["codebuild:BatchGetBuilds"],
    ["codebuild:BatchGetProjects"],
    ["codeartifact:GetPackageVersionAsset"],
    ["codecommit:GetBlob"],
    ["codecommit:GetCommit"],
    ["codecommit:GetFile"],
    ["codecommit:GitPull"],
    ["codepipeline:PollForJobs"],
    ["chime:GetChannelMessage"],
    ["chime:ListChannelMessages"],
    ["connect:BatchDescribeDataTableValue"],
    ["connect:EvaluateDataTableValues"],
    ["connect:GetAttachedFile"],
    ["connect:GetContactAttributes"],
    ["connect:GetFederationToken"],
    ["cognito-idp:AdminGetUser"],
    ["cognito-idp:DescribeUserPoolClient"],
    ["cognito-idp:DescribeIdentityProvider"],
    ["cognito-idp:ListUsers"],
    ["cognito-idp:ListUsersInGroup"],
    ["dynamodb:TransactGetItems"],
    ["deadline:AssumeQueueRoleForRead"],
    ["deadline:AssumeQueueRoleForUser"],
    ["datazone:GetEnvironmentCredentials"],
    ["datasync:StartTaskExecution", "s3:GetObject"],
    ["dms:ModifyEndpoint"],
    ["ec2:DescribeLaunchTemplateVersions"],
    ["ec2:DescribeInstanceAttribute"],
    ["elasticache:ModifyUser"],
    ["elasticloadbalancing:ModifyListener"],
    ["ebs:GetSnapshotBlock"],
    ["ecr:GetDownloadUrlForLayer"],
    ["ecs:DescribeTaskDefinition"],
    ["ecs:DescribeTasks"],
    ["emr-serverless:GetApplication"],
    ["emr-serverless:GetJobRun"],
    ["events:ListTargetsByRule"],
    ["execute-api:Invoke"],
    ["firehose:UpdateDestination"],
    ["frauddetector:GetEvent"],
    ["gameliftstreams:GetStreamSession"],
    ["gameliftstreams:GetStreamUrl"],
    ["gameliftstreams:ListStreamUrls"],
    ["globalaccelerator:UpdateEndpointGroup"],
    ["glue:GetConnection"],
    ["glue:GetJob"],
    ["glue:GetWorkflowRunProperties"],
    ["geo:GetDevicePosition"],
    ["geo:GetDevicePositionHistory"],
    ["greengrass:GetComponentVersionArtifact"],
    ["healthlake:ReadResource"],
    ["healthlake:SearchEverything"],
    ["healthlake:SearchWithGet"],
    ["healthlake:SearchWithPost"],
    ["imagebuilder:GetComponent"],
    ["iot:GetThingShadow"],
    ["iot:Publish"],
    ["iot:StartCommandExecution"],
    ["iotjobsdata:DescribeJobExecution"],
    ["iotjobsdata:StartNextPendingJobExecution"],
    ["iotjobsdata:UpdateJobExecution"],
    ["ivs:BatchGetStreamKey"],
    ["ivs:CreateStreamKey"],
    ["ivs:GetStreamKey"],
    ["ivs:UpdateChannel"],
    ["lakeformation:PutDataLakeSettings"],
    ["m2:GetSignedBluinsightsUrl"],
    ["mediaconnect:AddFlowOutputs"],
    ["mediaconnect:DescribeFlowSourceThumbnail"],
    ["mediaconnect:UpdateFlowOutput"],
    ["medialive:DescribeThumbnails"],
    ["medialive:UpdateChannel"],
    ["mediapackagev2:PutChannelPolicy"],
    ["mediapackagev2:PutOriginEndpointPolicy"],
    ["notifications:GetManagedNotificationEvent"],
    ["notifications:ListManagedNotificationEvents"],
    ["memorydb:UpdateUser"],
    ["mediapackage:RotateChannelCredentials"],
    ["mediapackage:RotateIngestEndpointCredentials"],
    ["neptune-db:GetStreamRecords"],
    ["neptune-db:ReadDataViaQuery"],
    ["neptune-graph:ReadDataViaQuery"],
    ["iot:Connect", "iot:Subscribe", "iot:Receive"],
    [
        "kafka-cluster:Connect",
        "kafka-cluster:DescribeTopic",
        "kafka-cluster:ReadData",
        "kafka-cluster:DescribeGroup",
        "kafka-cluster:AlterGroup",
    ],
    ["iotwireless:GetWirelessDevice"],
    ["iotsitewise:BatchGetAssetPropertyAggregates"],
    ["iotsitewise:BatchGetAssetPropertyValue"],
    ["iotsitewise:BatchGetAssetPropertyValueHistory"],
    ["iotsitewise:GetAssetPropertyAggregates"],
    ["iotsitewise:GetAssetPropertyValue"],
    ["iotsitewise:GetAssetPropertyValueHistory"],
    ["iotsitewise:GetInterpolatedAssetPropertyValues"],
    [
        "iottwinmaker:GetWorkspace",
        "iottwinmaker:GetComponentType",
        "iottwinmaker:GetPropertyValue",
    ],
    ["ivschat:CreateChatToken"],
    ["kinesis:GetRecords"],
    ["kinesisanalytics:DescribeApplication"],
    ["kinesisvideo:GetClip"],
    ["kinesisvideo:GetDASHStreamingSessionURL"],
    ["kinesisvideo:GetHLSStreamingSessionURL"],
    ["kinesisvideo:GetImages"],
    ["kinesisvideo:GetMedia"],
    ["kinesisvideo:GetMediaForFragmentList"],
    ["lambda:GetFunctionConfiguration"],
    ["lambda:GetLayerVersion"],
    ["lex:CreateExport", "lex:DescribeExport"],
    ["logs:FilterLogEvents"],
    ["logs:GetLogRecord"],
    ["logs:GetLogEvents"],
    ["logs:GetQueryResults"],
    ["medical-imaging:GetImageFrame"],
    ["medical-imaging:GetImageSetMetadata"],
    ["omics:GetReadSet"],
    ["invoicing:BatchGetInvoiceProfile"],
    ["invoicing:GetInvoicePDF"],
    ["invoicing:ListInvoiceSummaries"],
    ["lambda:GetFunction"],
    ["route53domains:GetDomainDetail"],
    ["rds-db:connect"],
    ["route53:ChangeResourceRecordSets"],
    ["rum:GetAppMonitorData"],
    ["sdb:GetAttributes"],
    ["sdb:Select"],
    ["s3:GetDataAccess"],
    ["s3vectors:GetVectors"],
    ["s3vectors:ListVectors", "s3vectors:GetVectors"],
    ["s3vectors:QueryVectors", "s3vectors:GetVectors"],
    ["s3express:CreateSession"],
    ["sagemaker:DescribeModel"],
    ["sagemaker:DescribeTrainingJob"],
    ["signer:StartSigningJob"],
    ["ses:GetSuppressedDestination"],
    ["ses:GetEmailTemplate"],
    ["ses:ListSuppressedDestinations"],
    ["sns:ListSubscriptions"],
    ["sns:ListSubscriptionsByTopic"],
    ["sqs:ReceiveMessage"],
    ["scheduler:GetSchedule"],
    ["servicediscovery:RegisterInstance"],
    ["pipes:DescribePipe"],
    ["profile:SearchProfiles"],
    ["ssm:GetDocument"],
    ["ssm:GetOpsItem"],
    ["ssm:GetParameterHistory"],
    ["states:DescribeStateMachine"],
    ["states:DescribeExecution"],
    ["states:GetActivityTask"],
    ["states:GetExecutionHistory"],
    ["sts:GetFederationToken"],
    ["tax:GetTaxRegistration"],
    ["tax:ListTaxRegistrations"],
    ["textract:GetDocumentAnalysis"],
    ["textract:GetDocumentTextDetection"],
    ["textract:GetExpenseAnalysis"],
    ["transcribe:GetTranscriptionJob"],
    ["transfer:ImportSshPublicKey"],
    ["translate:GetParallelData"],
    ["translate:GetTerminology"],
    ["vpc-lattice-svcs:Invoke"],
    ["wisdom:GetContent"],

    ["apigateway:POST"],
    ["apigateway:GET"],
    ["apigateway:PUT"],
    ["apigateway:PATCH"],
    ["apigateway:UpdateRestApiPolicy"],

    ["chime:CreateApiKey"],

    ["codebuild:CreateProject"],
    ["codebuild:UpdateProject"],

    ["s3:GetObject"],
    ["s3:PutObject"],

    ["codepipeline:CreatePipeline", "codebuild:CreateProject", "codepipeline:StartPipelineExecution"],

    ["codestar:CreateProject"],

    ["cloudformation:CreateStack"],
    ["cloudformation:UpdateStack"],
    ["cloudformation:UpdateStackSet"],
    ["cloudformation:SetStackPolicy"],
    ["cloudformation:CreateChangeSet", "cloudformation:ExecuteChangeSet"],

    ["cognito-identity:SetIdentityPoolRoles"],
    ["cognito-idp:CreateGroup", "cognito-idp:UpdateGroup"],
    ["cognito-idp:AdminEnableUser"],
    ["cognito-idp:AdminInitiateAuth"], 
    ["cognito-idp:AdminRespondToAuthChallenge"],

    ["datapipeline:CreatePipeline"],
    ["datapipeline:PutPipelineDefinition"],
    ["datapipeline:ActivatePipeline"],

    ["dynamodb:BatchGetItem"],
    ["dynamodb:GetItem"],
    ["dynamodb:Query"],
    ["dynamodb:Scan"],
    ["dynamodb:PartiQLSelect"],
    ["dynamodb:ExportTableToPointInTime"],
    ["dynamodb:RestoreTableFromBackup"],
    ["dynamodb:PutItem"],
    ["dynamodb:UpdateItem"],

    ["athena:GetQueryResults", "s3:GetObject"],

    ["ec2:CreateSnapshot"],
    ["ec2:RunInstances"],
    ["iam:AddRoleToInstanceProfile"],
    ["ec2:AssociateIamInstanceProfile", "ec2:DisassociateIamInstanceProfile"],
    ["ec2:ReplaceIamInstanceProfileAssociation"],
    ["autoscaling:CreateLaunchConfiguration", "autoscaling:CreateAutoScalingGroup"],
    ["ec2:DescribeLaunchTemplates", "ec2:DescribeLaunchTemplateVersions"],
    ["ec2:DescribeInstances", "ec2:RunInstances", "ec2:CreateSecurityGroup", "ec2:AuthorizeSecurityGroupIngress", "ec2:CreateTrafficMirrorTarget", "ec2:CreateTrafficMirrorSession", "ec2:CreateTrafficMirrorFilter", "ec2:CreateTrafficMirrorFilterRule"],

    ["ecr:GetAuthorizationToken", "ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer"],

    ["ecs:RunTask"],
    ["ecs:StartTask"],
    ["ecs:UpdateService"],
    ["ecs:CreateService"],
    ["ecs:UpdateServicePrimaryTaskSet"],

    ["elasticfilesystem:ClientMount"],
    ["elasticfilesystem:ClientMount", "elasticfilesystem:ClientRootAccess"],
    ["elasticfilesystem:ClientMount", "elasticfilesystem:ClientWrite"],
    ["elasticfilesystem:ClientMount", "elasticfilesystem:CreateAccessPoint"],

    ["elasticbeanstalk:CreateApplication", "elasticbeanstalk:CreateEnvironment", "elasticbeanstalk:CreateApplicationVersion", "elasticbeanstalk:UpdateEnvironment"],
    ["elasticbeanstalk:CreateApplicationVersion", "elasticbeanstalk:UpdateEnvironment", "cloudformation:GetTemplate", "cloudformation:DescribeStackResources", "cloudformation:DescribeStackResource", "autoscaling:DescribeAutoScalingGroups", "autoscaling:SuspendProcesses"],
    ["elasticbeanstalk:DescribeConfigurationSettings", "s3:CreateBucket", "s3:GetBucketLocation", "s3:GetObject", "s3:ListBucket"],

    ["scheduler:CreateSchedule", "scheduler:UpdateSchedule"],

    ["glue:CreateDevEndpoint"],
    ["glue:CreateJob"],
    ["glue:StartJobRun"],
    ["glue:CreateTrigger"],

    ["kms:CreateKey", "kms:ReplicateKey"],
    ["kms:Decrypt"],

    ["lambda:CreateFunction"],
    ["lambda:InvokeFunction"],
    ["lambda:InvokeFunctionUrl"],
    ["lambda:CreateEventSourceMapping"],

    ["rds:AddRoleToDBCluster"],
    ["rds:CreateDBInstance"],
    ["rds:AddRoleToDBInstance"],
    ["rds:RestoreDBInstanceFromDBSnapshot"],
    ["rds:DownloadDBLogFilePortion"],
    ["rds:StartExportTask"],

    ["redshift:ModifyCluster"],

    ["sns:Publish"],
    ["sns:Subscribe"],
    ["sns:Unsubscribe"],
    
    ["sqs:SendMessage"],
    ["sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:ChangeMessageVisibility"],
    ["sqs:PurgeQueue"],

    ["sso:DetachManagedPolicyFromPermissionSet"],
    ["sso:DetachCustomerManagedPolicyReferenceFromPermissionSet"],
    ["sso:DeleteInlinePolicyFromPermissionSet"],
    ["sso:DeletePermissionsBoundaryFromPermissionSet"],

    ["s3:PutBucketNotification"],
    ["s3:PutObject"],
    ["s3:GetObject"],

    ["sagemaker:CreateNotebookInstance"],
    ["sagemaker:CreateProcessingJob"],
    ["sagemaker:CreateTrainingJob"],
    ["sagemaker:CreateHyperParameterTuningJob"],

    ["ses:SendEmail"],
    ["ses:SendRawEmail"],
    ["ses:SendTemplatedEmail"],
    ["ses:SendBulkTemplatedEmail"],
    ["ses:SendBulkEmail"],
    ["ses:SendBounce"],
    ["ses:SendCustomVerificationEmail"],

    ["ssm:GetParameter"],
    ["ssm:GetParameters"],
    ["ssm:ListCommands"],
    ["ssm:GetCommandInvocation"],

    ["states:TestState"],
    ["states:CreateStateMachine"],
    ["states:RevealSecrets"],

    ["workdocs:CreateUser"],
    ["workdocs:AddResourcePermissions"],
    ["workdocs:AddUserToGroup"],

]


# Live-tested high-impact attack paths and their service-specific HackTricks
# evidence. Keep this deliberately narrow: documentation-only candidates do
# not belong here.
tested_risk_documentation = {
    "athena:CreatePresignedNotebookUrl": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "athena:StartCalculationExecution": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "glue:RunStatement": "aws-privilege-escalation/aws-glue-privesc/README.md",
    "backup:DeleteRecoveryPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:PutBackupVaultAccessPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "codebuild:StartCommandExecution": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "iot:OpenTunnel": "aws-services/aws-iot-core-enum.md",
    "iot:Publish": "aws-services/aws-iot-core-enum.md",
    "iot:StartCommandExecution": "aws-services/aws-iot-core-enum.md",
    "iotjobsdata:StartNextPendingJobExecution": "aws-services/aws-iot-core-enum.md",
    "iotjobsdata:UpdateJobExecution": "aws-services/aws-iot-core-enum.md",
    "ivs:CreateStreamKey": "aws-services/aws-ivs-enum.md",
    "ivs:UpdateChannel": "aws-services/aws-ivs-enum.md",
    "lakeformation:PutDataLakeSettings": "aws-services/aws-lake-formation-enum.md",
    "m2:GetSignedBluinsightsUrl": "aws-services/aws-mainframe-modernization-enum.md",
    "mediaconnect:AddFlowOutputs": "aws-services/aws-mediaconnect-enum.md",
    "mediaconnect:DescribeFlowSourceThumbnail": "aws-services/aws-mediaconnect-enum.md",
    "mediaconnect:UpdateFlowOutput": "aws-services/aws-mediaconnect-enum.md",
    "medialive:DescribeThumbnails": "aws-services/aws-medialive-enum.md",
    "medialive:UpdateChannel": "aws-services/aws-medialive-enum.md",
    "mediapackagev2:PutChannelPolicy": "aws-services/aws-mediapackage-v2-enum.md",
    "mediapackagev2:PutOriginEndpointPolicy": "aws-services/aws-mediapackage-v2-enum.md",
    "notifications:GetManagedNotificationEvent": "aws-services/aws-user-notifications-enum.md",
    "notifications:ListManagedNotificationEvents": "aws-services/aws-user-notifications-enum.md",
    "mq:CreateUser": "aws-privilege-escalation/aws-mq-privesc/README.md",
    "mq:UpdateUser": "aws-privilege-escalation/aws-mq-privesc/README.md",
    "lambda:GetFunction": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "route53domains:GetDomainDetail": "aws-privilege-escalation/aws-route53-domains-privesc/README.md",
    "s3:PutAccessPointPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3tables:PutTableBucketPolicy": "aws-services/aws-s3-tables-and-vectors-enum.md",
    "s3tables:PutTablePolicy": "aws-services/aws-s3-tables-and-vectors-enum.md",
    "servicediscovery:RegisterInstance": "aws-services/aws-cloud-map-enum.md",
    "signer:StartSigningJob": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "sts:GetFederationToken": "aws-privilege-escalation/aws-sts-privesc/README.md",
    "ssm:StartAutomationExecution": "aws-privilege-escalation/aws-ssm-privesc/README.md",
    "synthetics:StartCanaryDryRun": "aws-privilege-escalation/aws-synthetics-privesc/README.md",
    "textract:GetDocumentAnalysis": "aws-services/aws-textract-enum.md",
    "textract:GetDocumentTextDetection": "aws-services/aws-textract-enum.md",
    "textract:GetExpenseAnalysis": "aws-services/aws-textract-enum.md",
    "vpc-lattice-svcs:Invoke": "aws-services/aws-vpc-lattice-enum.md",
}


live_validated_disclosure_documentation = {
    "acm:ExportCertificate": "aws-services/aws-certificate-manager-acm-and-private-certificate-authority-pca.md",
    "account:GetContactInformation": "aws-services/aws-account-management-enum.md",
    "amplify:GetApp": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "amplify:GetArtifactUrl": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "amplify:GetJob": "aws-privilege-escalation/aws-amplify-privesc/README.md",
    "apigateway:GET": "aws-services/aws-api-gateway-enum.md",
    "apigateway:PATCH": "aws-post-exploitation/aws-api-gateway-post-exploitation/README.md",
    "athena:GetQueryExecution": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "athena:CreatePresignedNotebookUrl": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "athena:StartCalculationExecution": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "appstream:CreateStreamingURL": "aws-services/aws-workspaces-enum.md",
    "appconfig:GetHostedConfigurationVersion": "aws-services/aws-appconfig-enum.md",
    "appconfig:StartConfigurationSession": "aws-services/aws-appconfig-enum.md",
    "appconfig:GetLatestConfiguration": "aws-services/aws-appconfig-enum.md",
    "appsync:GraphQL": "aws-services/aws-appsync-enum.md",
    "appsync:ListApiKeys": "aws-services/aws-appsync-enum.md",
    "aps:PutResourcePolicy": "aws-services/aws-managed-prometheus-enum.md",
    "autoscaling:DescribeLaunchConfigurations": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "backup:CreateBackupAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:DescribeBackupAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "backup:StartRestoreJob": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "servicecatalog:CreateProvisioningArtifact": "aws-privilege-escalation/aws-service-catalog-privesc/README.md",
    "servicecatalog:ProvisionProduct": "aws-privilege-escalation/aws-service-catalog-privesc/README.md",
    "imagebuilder:CreateComponent": "aws-privilege-escalation/aws-ec2-image-builder-privesc/README.md",
    "imagebuilder:StartImagePipelineExecution": "aws-privilege-escalation/aws-ec2-image-builder-privesc/README.md",
    "codedeploy:CreateDeployment": "aws-privilege-escalation/aws-codedeploy-privesc/README.md",
    "codedeploy:GetDeploymentConfig": "aws-privilege-escalation/aws-codedeploy-privesc/README.md",
    "codedeploy:RegisterApplicationRevision": "aws-privilege-escalation/aws-codedeploy-privesc/README.md",
    "batch:DescribeJobDefinitions": "aws-services/aws-batch-enum.md",
    "bedrock:Retrieve": "aws-services/aws-bedrock-enum.md",
    "bedrock-agentcore:GetWorkloadAccessTokenForUserId": "aws-services/aws-bedrock-enum.md",
    "bedrock-agentcore:GetResourceApiKey": "aws-services/aws-bedrock-enum.md",
    "b2bi:GetProfile": "aws-services/aws-b2b-data-interchange-enum.md",
    "b2bi:GetTransformer": "aws-services/aws-b2b-data-interchange-enum.md",
    "cloudformation:DescribeStacks": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:DescribeChangeSet": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:GetTemplate": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:GetTemplateSummary": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudformation:ListExports": "aws-services/aws-cloudformation-and-codestar-enum.md",
    "cloudfront:GetDistribution": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:GetDistributionConfig": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:GetFunction": "aws-services/aws-cloudfront-enum.md",
    "cloudfront:ListDistributions": "aws-services/aws-cloudfront-enum.md",
    "glue:RunStatement": "aws-privilege-escalation/aws-glue-privesc/README.md",
    "cloudwatch:GetDashboard": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "cloudtrail:LookupEvents": "aws-services/aws-security-and-detection-services/aws-cloudtrail-enum.md",
    "ce:GetCostAndUsage": "aws-services/aws-security-and-detection-services/aws-cost-explorer-enum.md",
    "budgets:ViewBudget": "aws-services/aws-security-and-detection-services/aws-cost-explorer-enum.md",
    "aws-portal:ViewBilling": "aws-services/aws-security-and-detection-services/aws-cost-explorer-enum.md",
    "aws-marketplace:SearchAgreements": "aws-services/aws-marketplace-enum.md",
    "aws-marketplace:DescribeAgreement": "aws-services/aws-marketplace-enum.md",
    "aws-marketplace:GetAgreementTerms": "aws-services/aws-marketplace-enum.md",
    "codebuild:BatchGetBuilds": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "codebuild:BatchGetProjects": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "codebuild:StartCommandExecution": "aws-privilege-escalation/aws-codebuild-privesc/README.md",
    "codeartifact:GetPackageVersionAsset": "aws-services/aws-codeartifact-enum.md",
    "codecommit:GetBlob": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GetCommit": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GetFile": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codecommit:GitPull": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "codepipeline:PollForJobs": "aws-services/aws-datapipeline-codepipeline-codebuild-and-codecommit.md",
    "chime:GetChannelMessage": "aws-services/aws-chime-sdk-enum.md",
    "chime:ListChannelMessages": "aws-services/aws-chime-sdk-enum.md",
    "cassandra:Modify": "aws-services/aws-keyspaces-enum.md",
    "cassandra:Select": "aws-services/aws-keyspaces-enum.md",
    "connect:BatchDescribeDataTableValue": "aws-services/aws-connect-enum.md",
    "connect:EvaluateDataTableValues": "aws-services/aws-connect-enum.md",
    "connect:GetAttachedFile": "aws-services/aws-connect-enum.md",
    "connect:GetContactAttributes": "aws-services/aws-connect-enum.md",
    "connect:GetFederationToken": "aws-services/aws-connect-enum.md",
    "cognito-identity:UpdateIdentityPool": "aws-services/aws-cognito-enum/cognito-identity-pools.md",
    "cognito-idp:AdminGetUser": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:DescribeUserPoolClient": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:DescribeIdentityProvider": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:ListUsers": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "cognito-idp:ListUsersInGroup": "aws-services/aws-cognito-enum/cognito-user-pools.md",
    "dax:BatchGetItem": "aws-services/aws-dynamodb-enum.md",
    "dax:BatchWriteItem": "aws-services/aws-dynamodb-enum.md",
    "dax:ConditionCheckItem": "aws-services/aws-dynamodb-enum.md",
    "dax:DeleteItem": "aws-services/aws-dynamodb-enum.md",
    "dax:GetItem": "aws-services/aws-dynamodb-enum.md",
    "dax:PutItem": "aws-services/aws-dynamodb-enum.md",
    "dax:Query": "aws-services/aws-dynamodb-enum.md",
    "dax:Scan": "aws-services/aws-dynamodb-enum.md",
    "dax:UpdateItem": "aws-services/aws-dynamodb-enum.md",
    "devicefarm:GetRemoteAccessSession": "aws-services/aws-device-farm-enum.md",
    "devicefarm:ListArtifacts": "aws-services/aws-device-farm-enum.md",
    "dsql:DbConnect": "aws-services/aws-aurora-dsql-enum.md",
    "dsql:DbConnectAdmin": "aws-services/aws-aurora-dsql-enum.md",
    "dsql:PutClusterPolicy": "aws-services/aws-aurora-dsql-enum.md",
    "ec2-instance-connect:OpenTunnel": "aws-post-exploitation/aws-ec2-ebs-ssm-and-vpc-post-exploitation/aws-ec2-instance-connect-endpoint-backdoor.md",
    "ec2-instance-connect:SendSSHPublicKey": "aws-privilege-escalation/aws-ec2-privesc/README.md",
    "ec2-instance-connect:SendSerialConsoleSSHPublicKey": "aws-privilege-escalation/aws-ec2-privesc/README.md",
    "elasticfilesystem:ClientMount": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elasticfilesystem:ClientRootAccess": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elasticfilesystem:ClientWrite": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elasticfilesystem:CreateAccessPoint": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elasticfilesystem:DeleteFileSystemPolicy": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elasticfilesystem:PutFileSystemPolicy": "aws-privilege-escalation/aws-efs-privesc/README.md",
    "elemental-inference:ExportDictionaryEntries": "aws-services/aws-elemental-inference-enum.md",
    "elemental-inference:GetMetadata": "aws-services/aws-elemental-inference-enum.md",
    "elemental-inference:PutMedia": "aws-services/aws-elemental-inference-enum.md",
    "elemental-inference:UpdateDictionary": "aws-services/aws-elemental-inference-enum.md",
    "entityresolution:PutPolicy": "aws-services/aws-entity-resolution-enum.md",
    "dynamodb:PutResourcePolicy": "aws-privilege-escalation/aws-dynamodb-privesc/README.md",
    "dynamodb:BatchGetItem": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:GetItem": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:Query": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:Scan": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "dynamodb:TransactGetItems": "aws-post-exploitation/aws-dynamodb-post-exploitation/README.md",
    "docdb-elastic:UpdateCluster": "aws-services/aws-documentdb-enum/README.md",
    "deadline:AssumeQueueRoleForRead": "aws-services/aws-deadline-cloud-enum.md",
    "deadline:AssumeQueueRoleForUser": "aws-services/aws-deadline-cloud-enum.md",
    "datazone:GetEnvironmentCredentials": "aws-services/aws-datazone-enum.md",
    "datasync:StartTaskExecution": "aws-services/aws-datasync-enum.md",
    "dms:ModifyEndpoint": "aws-services/aws-dms-enum.md",
    "ec2:ModifyInstanceAttribute": "aws-privilege-escalation/aws-ec2-privesc/README.md",
    "ec2:DescribeLaunchTemplateVersions": "aws-privilege-escalation/aws-ec2-privesc/README.md",
    "ec2:DescribeInstanceAttribute": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "elasticache:ModifyUser": "aws-services/aws-elasticache.md",
    "ebs:GetSnapshotBlock": "aws-privilege-escalation/aws-ebs-privesc/README.md",
    "ecr:GetDownloadUrlForLayer": "aws-post-exploitation/aws-ecr-post-exploitation/README.md",
    "ecr-public:SetRepositoryPolicy": "aws-privilege-escalation/aws-ecr-privesc/README.md",
    "ecs:DescribeTaskDefinition": "aws-services/aws-ecs-enum.md",
    "ecs:DescribeTasks": "aws-services/aws-ecs-enum.md",
    "events:PutEvents": "aws-privilege-escalation/aws-eventbridge-privesc/README.md",
    "events:PutTargets": "aws-privilege-escalation/aws-eventbridge-privesc/README.md",
    "fis:UpdateExperimentTemplate": "aws-privilege-escalation/aws-fis-privesc/README.md",
    "fis:StartExperiment": "aws-privilege-escalation/aws-fis-privesc/README.md",
    "firehose:UpdateDestination": "aws-services/aws-kinesis-data-firehose-enum.md",
    "frauddetector:GetEvent": "aws-services/aws-fraud-detector-enum.md",
    "gamelift:GetComputeAccess": "aws-services/aws-gamelift-enum.md",
    "gameliftstreams:CreateStreamSessionAdminShell": "aws-services/aws-gamelift-streams-enum.md",
    "gameliftstreams:GetStreamSession": "aws-services/aws-gamelift-streams-enum.md",
    "gameliftstreams:GetStreamUrl": "aws-services/aws-gamelift-streams-enum.md",
    "gameliftstreams:ListStreamUrls": "aws-services/aws-gamelift-streams-enum.md",
    "globalaccelerator:UpdateEndpointGroup": "aws-services/aws-global-accelerator-enum.md",
    "emr-serverless:GetApplication": "aws-services/aws-emr-enum.md",
    "emr-serverless:GetJobRun": "aws-services/aws-emr-enum.md",
    "events:ListTargetsByRule": "aws-services/eventbridgescheduler-enum.md",
    "elasticloadbalancing:ModifyListener": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "eks:CreateAccessEntry": "aws-post-exploitation/aws-eks-post-exploitation/README.md",
    "eks:AssociateAccessPolicy": "aws-post-exploitation/aws-eks-post-exploitation/README.md",
    "eks-auth:AssumeRoleForPodIdentity": "aws-post-exploitation/aws-eks-post-exploitation/README.md",
    "es:UpdateDomainConfig": "aws-services/aws-opensearch-enum.md",
    "iam:CreateAccessKey": "aws-privilege-escalation/aws-iam-privesc/README.md",
    "memorydb:UpdateUser": "aws-services/aws-memorydb-enum.md",
    "mediapackage:RotateChannelCredentials": "aws-privilege-escalation/aws-mediapackage-privesc/README.md",
    "mediapackage:RotateIngestEndpointCredentials": "aws-privilege-escalation/aws-mediapackage-privesc/README.md",
    "neptune-db:GetStreamRecords": "aws-services/aws-neptune-enum.md",
    "neptune-db:ReadDataViaQuery": "aws-services/aws-neptune-enum.md",
    "neptune-graph:ReadDataViaQuery": "aws-services/aws-neptune-enum.md",
    "execute-api:Invoke": "aws-services/aws-api-gateway-enum.md",
    "glue:GetConnection": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "glue:GetJob": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "glue:GetWorkflowRunProperties": "aws-post-exploitation/aws-glue-post-exploitation/README.md",
    "geo:GetDevicePosition": "aws-services/aws-location-service-enum.md",
    "geo:GetDevicePositionHistory": "aws-services/aws-location-service-enum.md",
    "grafana:CreateWorkspaceApiKey": "aws-services/aws-managed-grafana-enum.md",
    "grafana:CreateWorkspaceServiceAccountToken": "aws-services/aws-managed-grafana-enum.md",
    "greengrass:GetComponentVersionArtifact": "aws-services/aws-greengrass-enum.md",
    "healthlake:ReadResource": "aws-services/aws-healthlake-enum.md",
    "healthlake:SearchEverything": "aws-services/aws-healthlake-enum.md",
    "healthlake:SearchWithGet": "aws-services/aws-healthlake-enum.md",
    "healthlake:SearchWithPost": "aws-services/aws-healthlake-enum.md",
    "imagebuilder:GetComponent": "aws-services/aws-ec2-image-builder-enum.md",
    "iot:Connect": "aws-services/aws-iot-core-enum.md",
    "iot:GetThingShadow": "aws-services/aws-iot-core-enum.md",
    "iot:Receive": "aws-services/aws-iot-core-enum.md",
    "iot:StartCommandExecution": "aws-services/aws-iot-core-enum.md",
    "iot:Subscribe": "aws-services/aws-iot-core-enum.md",
    "iotjobsdata:DescribeJobExecution": "aws-services/aws-iot-core-enum.md",
    "iotjobsdata:StartNextPendingJobExecution": "aws-services/aws-iot-core-enum.md",
    "iotjobsdata:UpdateJobExecution": "aws-services/aws-iot-core-enum.md",
    "iotwireless:GetWirelessDevice": "aws-services/aws-iot-wireless-enum.md",
    "iotsitewise:BatchGetAssetPropertyAggregates": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:BatchGetAssetPropertyValue": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:BatchGetAssetPropertyValueHistory": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:GetAssetPropertyAggregates": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:GetAssetPropertyValue": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:GetAssetPropertyValueHistory": "aws-services/aws-iot-sitewise-enum.md",
    "iotsitewise:GetInterpolatedAssetPropertyValues": "aws-services/aws-iot-sitewise-enum.md",
    "iottwinmaker:GetComponentType": "aws-services/aws-iot-twinmaker-enum.md",
    "iottwinmaker:GetPropertyValue": "aws-services/aws-iot-twinmaker-enum.md",
    "iottwinmaker:GetWorkspace": "aws-services/aws-iot-twinmaker-enum.md",
    "ivs:BatchGetStreamKey": "aws-services/aws-ivs-enum.md",
    "ivs:CreateStreamKey": "aws-services/aws-ivs-enum.md",
    "ivs:GetStreamKey": "aws-services/aws-ivs-enum.md",
    "ivs:UpdateChannel": "aws-services/aws-ivs-enum.md",
    "ivschat:CreateChatToken": "aws-services/aws-ivs-chat-enum.md",
    "lakeformation:PutDataLakeSettings": "aws-services/aws-lake-formation-enum.md",
    "m2:GetSignedBluinsightsUrl": "aws-services/aws-mainframe-modernization-enum.md",
    "mediaconnect:AddFlowOutputs": "aws-services/aws-mediaconnect-enum.md",
    "mediaconnect:DescribeFlowSourceThumbnail": "aws-services/aws-mediaconnect-enum.md",
    "mediaconnect:UpdateFlowOutput": "aws-services/aws-mediaconnect-enum.md",
    "medialive:DescribeThumbnails": "aws-services/aws-medialive-enum.md",
    "medialive:UpdateChannel": "aws-services/aws-medialive-enum.md",
    "mediapackagev2:PutChannelPolicy": "aws-services/aws-mediapackage-v2-enum.md",
    "mediapackagev2:PutOriginEndpointPolicy": "aws-services/aws-mediapackage-v2-enum.md",
    "notifications:GetManagedNotificationEvent": "aws-services/aws-user-notifications-enum.md",
    "notifications:ListManagedNotificationEvents": "aws-services/aws-user-notifications-enum.md",
    "mq:CreateUser": "aws-privilege-escalation/aws-mq-privesc/README.md",
    "mq:UpdateUser": "aws-privilege-escalation/aws-mq-privesc/README.md",
    "s3tables:PutTableBucketPolicy": "aws-services/aws-s3-tables-and-vectors-enum.md",
    "s3tables:PutTablePolicy": "aws-services/aws-s3-tables-and-vectors-enum.md",
    "servicediscovery:RegisterInstance": "aws-services/aws-cloud-map-enum.md",
    "kafka:UpdateSecurity": "aws-privilege-escalation/aws-msk-privesc/README.md",
    "kafka-cluster:Connect": "aws-services/aws-msk-enum.md",
    "kafka-cluster:DescribeTopic": "aws-services/aws-msk-enum.md",
    "kafka-cluster:ReadData": "aws-services/aws-msk-enum.md",
    "kafka-cluster:DescribeGroup": "aws-services/aws-msk-enum.md",
    "kafka-cluster:AlterGroup": "aws-services/aws-msk-enum.md",
    "kinesis:GetRecords": "aws-services/aws-kinesis-data-streams-enum.md",
    "textract:GetDocumentAnalysis": "aws-services/aws-textract-enum.md",
    "textract:GetDocumentTextDetection": "aws-services/aws-textract-enum.md",
    "textract:GetExpenseAnalysis": "aws-services/aws-textract-enum.md",
    "vpc-lattice-svcs:Invoke": "aws-services/aws-vpc-lattice-enum.md",
    "kinesisanalytics:DescribeApplication": "aws-services/aws-managed-flink-enum.md",
    "kinesisvideo:GetClip": "aws-services/aws-kinesis-video-streams-enum.md",
    "kinesisvideo:GetDASHStreamingSessionURL": "aws-services/aws-kinesis-video-streams-enum.md",
    "kinesisvideo:GetHLSStreamingSessionURL": "aws-services/aws-kinesis-video-streams-enum.md",
    "kinesisvideo:GetImages": "aws-services/aws-kinesis-video-streams-enum.md",
    "kinesisvideo:GetMedia": "aws-services/aws-kinesis-video-streams-enum.md",
    "kinesisvideo:GetMediaForFragmentList": "aws-services/aws-kinesis-video-streams-enum.md",
    "lambda:GetFunctionConfiguration": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "lambda:GetLayerVersion": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "lightsail:CreateBucketAccessKey": "aws-privilege-escalation/aws-lightsail-privesc/README.md",
    "lightsail:DownloadDefaultKeyPair": "aws-privilege-escalation/aws-lightsail-privesc/README.md",
    "lightsail:GetInstanceAccessDetails": "aws-privilege-escalation/aws-lightsail-privesc/README.md",
    "lightsail:UpdateBucket": "aws-privilege-escalation/aws-lightsail-privesc/README.md",
    "lex:CreateExport": "aws-services/aws-lex-v2-enum.md",
    "lex:DescribeExport": "aws-services/aws-lex-v2-enum.md",
    "logs:FilterLogEvents": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetLogRecord": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetLogEvents": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "logs:GetQueryResults": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "medical-imaging:GetImageFrame": "aws-services/aws-healthimaging-enum.md",
    "medical-imaging:GetImageSetMetadata": "aws-services/aws-healthimaging-enum.md",
    "omics:GetReadSet": "aws-services/aws-healthomics-enum.md",
    "invoicing:BatchGetInvoiceProfile": "aws-services/aws-invoicing-enum.md",
    "invoicing:GetInvoicePDF": "aws-services/aws-invoicing-enum.md",
    "invoicing:ListInvoiceSummaries": "aws-services/aws-invoicing-enum.md",
    "sagemaker:DescribeModel": "aws-services/aws-sagemaker-enum/README.md",
    "sagemaker:DescribeTrainingJob": "aws-services/aws-sagemaker-enum/README.md",
    "sagemaker:UpdateNotebookInstanceLifecycleConfig": "aws-persistence/aws-sagemaker-persistence/README.md",
    "secretsmanager:PutResourcePolicy": "aws-privilege-escalation/aws-secrets-manager-privesc/README.md",
    "s3:GetDataAccess": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "s3:CreateAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3:GetAccessPoint": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3:PutAccessPointPolicy": "aws-post-exploitation/aws-backup-post-exploitation/README.md",
    "s3vectors:GetVectors": "aws-services/aws-bedrock-enum.md",
    "s3vectors:ListVectors": "aws-services/aws-bedrock-enum.md",
    "s3vectors:QueryVectors": "aws-services/aws-bedrock-enum.md",
    "s3express:CreateSession": "aws-services/aws-s3-athena-and-glacier-enum.md",
    "secretsmanager:GetSecretValue": "aws-services/aws-secrets-manager-enum.md",
    "ses:GetSuppressedDestination": "aws-services/aws-ses-enum.md",
    "ses:GetEmailTemplate": "aws-services/aws-ses-enum.md",
    "ses:ListSuppressedDestinations": "aws-services/aws-ses-enum.md",
    "signer:StartSigningJob": "aws-privilege-escalation/aws-lambda-privesc/README.md",
    "sns:ListSubscriptions": "aws-services/aws-sns-enum.md",
    "sns:ListSubscriptionsByTopic": "aws-services/aws-sns-enum.md",
    "sqs:ReceiveMessage": "aws-post-exploitation/aws-sqs-post-exploitation/README.md",
    "scheduler:GetSchedule": "aws-services/eventbridgescheduler-enum.md",
    "sns:SetTopicAttributes": "aws-post-exploitation/aws-sns-post-exploitation/README.md",
    "sqs:SetQueueAttributes": "aws-post-exploitation/aws-sqs-post-exploitation/README.md",
    "pipes:DescribePipe": "aws-services/eventbridgescheduler-enum.md",
    "profile:SearchProfiles": "aws-services/aws-connect-customer-profiles-enum.md",
    "rum:GetAppMonitorData": "aws-services/aws-security-and-detection-services/aws-cloudwatch-enum.md",
    "sdb:GetAttributes": "aws-services/aws-simpledb-enum.md",
    "sdb:Select": "aws-services/aws-simpledb-enum.md",
    "rolesanywhere:UpdateTrustAnchor": "aws-privilege-escalation/aws-sts-privesc/README.md",
    "route53:ChangeResourceRecordSets": "aws-services/aws-route53-enum.md",
    "route53domains:GetDomainDetail": "aws-privilege-escalation/aws-route53-domains-privesc/README.md",
    "rds:ModifyDBInstance": "aws-privilege-escalation/aws-rds-privesc/README.md",
    "rds-db:connect": "aws-privilege-escalation/aws-rds-privesc/README.md",
    "redshift:GetClusterCredentials": "aws-privilege-escalation/aws-redshift-privesc/README.md",
    "redshift:GetClusterCredentialsWithIAM": "aws-privilege-escalation/aws-redshift-privesc/README.md",
    "ssm:GetDocument": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "ssm:GetOpsItem": "aws-services/aws-ec2-ebs-elb-ssm-vpc-and-vpn-enum/README.md",
    "ssm:StartAutomationExecution": "aws-privilege-escalation/aws-ssm-privesc/README.md",
    "ssm:GetParameterHistory": "aws-privilege-escalation/aws-ssm-privesc/README.md",
    "states:DescribeStateMachine": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:DescribeExecution": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:GetActivityTask": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "states:GetExecutionHistory": "aws-post-exploitation/aws-stepfunctions-post-exploitation/README.md",
    "sts:GetFederationToken": "aws-privilege-escalation/aws-sts-privesc/README.md",
    "tax:GetTaxRegistration": "aws-services/aws-tax-settings-enum.md",
    "tax:ListTaxRegistrations": "aws-services/aws-tax-settings-enum.md",
    "transcribe:GetTranscriptionJob": "aws-services/aws-transcribe-enum.md",
    "transfer:ImportSshPublicKey": "aws-privilege-escalation/aws-transfer-family-privesc/README.md",
    "translate:GetParallelData": "aws-services/aws-translate-enum.md",
    "translate:GetTerminology": "aws-services/aws-translate-enum.md",
    "wisdom:GetContent": "aws-services/aws-q-in-connect-enum.md",
}
