"""GCP attack-path permissions that supplement the generic risk classifier.

Single-item combinations are intentional: this module is also consumed by
older CloudPEASS integrations. Multi-item combinations model paths that need
all listed permissions before they become critical.
"""


very_sensitive_combinations = [
    # IAM policy changes and principal impersonation.
    ["*.setIamPolicy"],
    ["iam.serviceAccounts.actAs"],
    ["iam.serviceAccounts.getAccessToken"],
    [
        "iam.serviceAccounts.implicitDelegation",
        "iam.serviceAccounts.getAccessToken",
    ],
    ["iam.serviceAccounts.signBlob"],
    ["iam.serviceAccounts.signJwt"],
    ["iam.serviceAccountKeys.create"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.create"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.undelete"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.update"],
    ["iam.googleapis.com/workloadIdentityPools.undelete"],
    ["iam.googleapis.com/workloadIdentityPools.update"],
    ["iam.roles.update"],

    # Credential, secret, and decryption material.
    ["apikeys.keys.getKeyString"],
    ["cloudkms.cryptoKeyVersions.useToDecrypt"],
    ["cloudkms.cryptoKeyVersions.useToDecryptViaDelegation"],
    ["integrations.authConfigs.get"],
    ["secretmanager.versions.access"],
    ["storage.hmacKeys.create"],

    # Direct code execution or supply-chain replacement.
    ["appengine.instances.enableDebug"],
    ["cloudbuild.builds.create"],
    [
        "cloudfunctions.functions.create",
        "cloudfunctions.functions.sourceCodeSet",
        "iam.serviceAccounts.actAs",
    ],
    ["cloudfunctions.functions.update", "iam.serviceAccounts.actAs"],
    ["composer.environments.create", "iam.serviceAccounts.actAs"],
    ["composer.environments.executeAirflowCommand"],
    ["composer.environments.update"],
    ["compute.projects.setCommonInstanceMetadata"],
    ["compute.instances.setMetadata"],
    ["compute.instances.osLogin"],
    ["compute.instances.osAdminLogin"],
    ["osconfig.patchDeployments.create"],
    ["osconfig.patchJobs.exec"],
    ["run.jobs.run", "run.jobs.runWithOverrides"],
    [
        "workflows.workflows.create",
        "iam.serviceAccounts.actAs",
        "workflows.executions.create",
    ],

    # GKE RBAC escalation, secret access, and workload execution.
    ["container.roles.escalate"],
    ["container.clusterRoles.escalate"],
    ["container.roles.bind"],
    ["container.clusterRoles.bind"],
    ["container.cronJobs.create"],
    ["container.cronJobs.update"],
    ["container.daemonSets.create"],
    ["container.daemonSets.update"],
    ["container.deployments.create"],
    ["container.deployments.update"],
    ["container.jobs.create"],
    ["container.jobs.update"],
    ["container.pods.create"],
    ["container.pods.update"],
    ["container.replicaSets.create"],
    ["container.replicaSets.update"],
    ["container.replicationControllers.create"],
    ["container.replicationControllers.update"],
    ["container.scheduledJobs.create"],
    ["container.scheduledJobs.update"],
    ["container.statefulSets.create"],
    ["container.statefulSets.update"],
    ["container.secrets.get"],
    ["container.secrets.list"],
    ["container.nodes.proxy"],
    ["container.pods.exec"],
    ["container.serviceAccounts.createToken"],
    # Deployment services can execute as more privileged service accounts.
    [
        "dataproc.clusters.get",
        "dataproc.clusters.use",
        "dataproc.jobs.create",
        "dataproc.jobs.get",
        "dataproc.jobs.list",
        "storage.objects.create",
        "storage.objects.get",
    ],
    [
        "dataflow.jobs.create",
        "resourcemanager.projects.get",
        "iam.serviceAccounts.actAs",
    ],
    ["deploymentmanager.deployments.create"],
    ["deploymentmanager.deployments.update"],

    # Database account takeover.
    ["cloudsql.users.create"],
    ["cloudsql.users.update"],

    # Registering a Migration Center discovery client with a caller-specified
    # service account impersonates it (actAs-gated).
    [
        "migrationcenter.discoveryClients.create",
        "iam.serviceAccounts.actAs",
    ],
]


sensitive_combinations = [
    # Credentials or identity-related changes that usually need more context.
    ["agentidentity.authProviders.retrieveCredentials"],
    ["agentidentity.authProviders.update"],
    ["aiplatform.pipelineJobs.get"],
    ["aiplatform.pipelineJobs.list"],
    ["integrations.integrations.invoke"],
    ["apikeys.keys.create"],
    ["appengine.versions.get"],
    ["appengine.versions.list"],
    ["artifactregistry.repositories.uploadArtifacts"],
    ["iam.serviceAccounts.getOpenIdToken"],
    ["cloudbuild.repositories.accessReadToken"],
    ["cloudbuild.repositories.accessReadWriteToken"],
    ["cloudbuild.builds.get"],
    ["cloudbuild.builds.list"],
    ["cloudscheduler.jobs.get"],
    ["cloudscheduler.jobs.list"],
    ["cloudtasks.tasks.get"],
    ["cloudtasks.tasks.list"],
    ["gsuiteaddons.deployments.update"],
    ["container.clusters.get"],
    ["container.clusters.getCredentials"],
    ["container.pods.attach"],
    ["container.pods.getLogs"],
    ["container.pods.portForward"],
    ["container.pods.proxy"],
    ["container.services.proxy"],
    ["orgpolicy.policy.set"],

    # Direct data access, invocation, or message injection.
    ["artifactregistry.repositories.downloadArtifacts"],
    ["bigquery.tables.getData"],
    ["cloudfunctions.functions.sourceCodeGet"],
    ["cloudsql.instances.connect"],
    ["cloudsql.instances.export"],
    ["cloudsql.instances.executeSql", "cloudsql.instances.login"],
    ["compute.projects.get"],
    ["compute.instanceSettings.get"],
    ["compute.instances.get"],
    ["compute.instances.list"],
    ["compute.instanceTemplates.get"],
    ["compute.instanceTemplates.list"],
    ["compute.machineImages.get"],
    ["compute.machineImages.list"],
    ["compute.instances.getSerialPortOutput"],
    ["datastore.entities.create"],
    ["datastore.entities.delete"],
    ["datastore.entities.get"],
    ["datastore.entities.update"],
    ["dns.changes.create", "dns.resourceRecordSets.create"],
    ["dns.changes.create", "dns.resourceRecordSets.update"],
    ["dns.changes.create", "dns.resourceRecordSets.delete"],
    ["healthcare.dicomStores.dicomWebDelete"],
    ["healthcare.dicomStores.dicomWebRead"],
    ["healthcare.dicomStores.dicomWebWrite"],
    ["healthcare.fhirResources.create"],
    ["healthcare.fhirResources.delete"],
    ["healthcare.fhirResources.get"],
    ["healthcare.fhirResources.patch"],
    ["healthcare.fhirResources.update"],
    ["healthcare.fhirStores.searchResources"],
    ["healthcare.hl7V2Messages.create"],
    ["healthcare.hl7V2Messages.delete"],
    ["healthcare.hl7V2Messages.get"],
    ["healthcare.hl7V2Messages.ingest"],
    ["logging.logEntries.list", "logging.views.access"],
    ["pubsub.subscriptions.consume"],
    ["pubsub.topics.publish"],
    ["redis.instances.getAuthString"],
    ["run.configurations.get"],
    ["run.configurations.list"],
    ["run.executions.get"],
    ["run.executions.list"],
    ["run.jobs.get"],
    ["run.jobs.list"],
    ["run.revisions.get"],
    ["run.revisions.list"],
    ["run.routes.invoke"],
    ["run.services.get"],
    ["run.services.list"],
    ["run.tasks.get"],
    ["run.tasks.list"],
    ["secretmanager.versions.add"],
    ["secretmanager.versions.destroy"],
    ["source.repos.get"],
    ["source.repos.update"],
    ["spanner.databases.read", "spanner.sessions.create"],
    ["spanner.databases.select", "spanner.sessions.create"],
    ["spanner.databases.write", "spanner.sessions.create"],
    ["storage.objects.create"],
    ["storage.objects.delete"],
    ["storage.objects.get"],
    ["workflows.executions.create"],
    ["workflows.executions.get"],
    ["workflows.executions.list"],
    ["workflows.stepEntries.get"],
    ["workflows.stepEntries.list"],
    ["workflows.workflows.get"],
    ["workflows.workflows.list"],

    # Security-control or evidence tampering.
    ["cloudbuild.builds.approve"],
    ["logging.logs.delete"],
    ["logging.sinks.delete"],
    ["logging.logMetrics.delete"],
    ["monitoring.alertPolicies.delete"],
    ["monitoring.notificationChannels.delete"],
    ["securitycenter.findings.setMute"],
    ["securitycenter.findings.bulkMuteUpdate"],
]


# Every Critical/High exact permission or combination above must match one of
# these evidence families. The referenced HackTricks Cloud page contains the
# concrete abuse or data-access procedure; tests prevent adding an unreferenced
# high-severity permission by accident.
risk_documentation = (
    (
        "agentidentity.authProviders.retrieveCredentials",
        "gcp-to-workspace-pivoting/gcp-agent-identity-auth-manager-privesc.md",
    ),
    (
        "agentidentity.authProviders.update",
        "gcp-to-workspace-pivoting/gcp-agent-identity-auth-manager-privesc.md",
    ),
    (
        "aiplatform.pipelineJobs.get",
        "gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md",
    ),
    (
        "aiplatform.pipelineJobs.list",
        "gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md",
    ),
    (
        "iam.serviceAccounts.getAccessToken",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "iam.serviceAccounts.signBlob",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "iam.serviceAccounts.signJwt",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "resourcemanager.organizations.setIamPolicy",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "gsuiteaddons.deployments.update",
        "gcp-to-workspace-pivoting/gcp-workspace-addons-privesc.md",
    ),
    (
        "integrations.integrations.invoke",
        "gcp-to-workspace-pivoting/gcp-application-integration-privesc.md",
    ),
    (
        "integrations.authConfigs.get",
        "gcp-to-workspace-pivoting/gcp-application-integration-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.create",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.undelete",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.update",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPools.undelete",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPools.update",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    ("*.setIamPolicy", "gcp-privilege-escalation/gcp-misc-perms-privesc.md"),
    ("cloudbuild.builds.approve", "gcp-post-exploitation/gcp-cloud-build-post-exploitation.md"),
    ("cloudfunctions.functions.sourceCodeGet", "gcp-post-exploitation/gcp-cloud-functions-post-exploitation.md"),
    ("cloudkms.cryptoKeyVersions.destroy", "gcp-post-exploitation/gcp-kms-post-exploitation.md"),
    ("dataflow.jobs.create", "gcp-post-exploitation/gcp-dataflow-post-exploitation.md"),
    ("logging.views.access", "gcp-post-exploitation/gcp-app-engine-post-exploitation.md"),
    ("pubsub.topics.publish", "gcp-post-exploitation/gcp-pub-sub-post-exploitation.md"),
    ("resourcemanager.projects.get", "gcp-post-exploitation/gcp-dataflow-post-exploitation.md"),
    ("apikeys.*", "gcp-privilege-escalation/gcp-serviceusage-privesc.md"),
    (
        "appengine.versions.get",
        "gcp-post-exploitation/gcp-app-engine-post-exploitation.md",
    ),
    (
        "appengine.versions.list",
        "gcp-post-exploitation/gcp-app-engine-post-exploitation.md",
    ),
    ("appengine.*", "gcp-privilege-escalation/gcp-appengine-privesc.md"),
    ("artifactregistry.*", "gcp-privilege-escalation/gcp-artifact-registry-privesc.md"),
    ("bigquery.*", "gcp-privilege-escalation/gcp-bigquery-privesc.md"),
    ("bigtable.*", "gcp-post-exploitation/gcp-bigtable-post-exploitation.md"),
    ("clientauthconfig.*", "gcp-privilege-escalation/gcp-clientauthconfig-privesc.md"),
    ("cloudbuild.*", "gcp-privilege-escalation/gcp-cloudbuild-privesc.md"),
    ("cloudscheduler.*", "gcp-privilege-escalation/gcp-cloudscheduler-privesc.md"),
    ("cloudtasks.*", "gcp-privilege-escalation/gcp-cloudtasks-privesc.md"),
    ("cloudfunctions.*", "gcp-privilege-escalation/gcp-cloudfunctions-privesc.md"),
    ("cloudkms.*", "gcp-privilege-escalation/gcp-kms-privesc.md"),
    ("cloudsql.*", "gcp-post-exploitation/gcp-cloud-sql-post-exploitation.md"),
    ("composer.*", "gcp-privilege-escalation/gcp-composer-privesc.md"),
    (
        "compute.instances.getSerialPortOutput",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.projects.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceSettings.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instances.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instances.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceTemplates.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceTemplates.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.machineImages.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.machineImages.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    ("compute.*", "gcp-privilege-escalation/gcp-compute-privesc/README.md"),
    ("container.*", "gcp-privilege-escalation/gcp-container-privesc.md"),
    ("datastore.*", "gcp-privilege-escalation/gcp-firebase-privesc.md"),
    ("dataflow.*", "gcp-privilege-escalation/gcp-dataflow-privesc.md"),
    ("dataproc.*", "gcp-privilege-escalation/gcp-dataproc-privesc.md"),
    ("deploymentmanager.*", "gcp-privilege-escalation/gcp-deploymentmaneger-privesc.md"),
    ("dns.*", "gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md"),
    ("iam.*", "gcp-privilege-escalation/gcp-iam-privesc.md"),
    ("healthcare.*", "gcp-post-exploitation/gcp-healthcare-post-exploitation.md"),
    ("logging.*", "gcp-post-exploitation/gcp-logging-post-exploitation.md"),
    ("monitoring.*", "gcp-post-exploitation/gcp-monitoring-post-exploitation.md"),
    ("orgpolicy.*", "gcp-privilege-escalation/gcp-orgpolicy-privesc.md"),
    ("osconfig.*", "gcp-privilege-escalation/gcp-compute-privesc/README.md"),
    ("pubsub.*", "gcp-privilege-escalation/gcp-pubsub-privesc.md"),
    ("redis.*", "gcp-post-exploitation/gcp-memorystore-post-exploitation.md"),
    ("resourcemanager.*", "gcp-privilege-escalation/gcp-resourcemanager-privesc.md"),
    ("run.*", "gcp-privilege-escalation/gcp-run-privesc.md"),
    ("secretmanager.*", "gcp-privilege-escalation/gcp-secretmanager-privesc.md"),
    ("securitycenter.*", "gcp-post-exploitation/gcp-security-post-exploitation.md"),
    ("source.*", "gcp-privilege-escalation/gcp-sourcerepos-privesc.md"),
    ("spanner.*", "gcp-post-exploitation/gcp-spanner-post-exploitation.md"),
    ("storage.*", "gcp-privilege-escalation/gcp-storage-privesc.md"),
    ("workflows.*", "gcp-privilege-escalation/gcp-workflows-privesc.md"),
    # Newer service attack paths. Some are documented on the service enum pages
    # under gcp-services/ rather than a dedicated privesc/post-exploitation page.
    ("baremetalsolution.*", "gcp-services/gcp-bare-metal-solution-enum.md"),
    ("biglake.*", "gcp-services/gcp-biglake-enum.md"),
    ("cloudtrace.*", "gcp-services/gcp-trace-profiler-error-reporting-enum.md"),
    ("contactcenterinsights.*", "gcp-services/gcp-contact-center-insights-enum.md"),
    ("discoveryengine.*", "gcp-services/gcp-vertex-ai-search-enum.md"),
    ("domains.*", "gcp-post-exploitation/gcp-cloud-domains-post-exploitation.md"),
    ("errorreporting.*", "gcp-services/gcp-trace-profiler-error-reporting-enum.md"),
    ("krmapihosting.*", "gcp-services/gcp-config-controller-enum.md"),
    ("livestream.*", "gcp-post-exploitation/gcp-live-stream-post-exploitation.md"),
    ("looker.*", "gcp-services/gcp-looker-enum.md"),
    ("managedkafka.*", "gcp-services/gcp-managed-kafka-enum.md"),
    ("migrationcenter.*", "gcp-services/gcp-migration-center-enum.md"),
    ("netapp.*", "gcp-services/gcp-netapp-volumes-enum.md"),
    ("networksecurity.*", "gcp-privilege-escalation/gcp-networksecurity-privesc.md"),
    ("networkservices.*", "gcp-privilege-escalation/gcp-networkservices-privesc.md"),
    ("parallelstore.*", "gcp-privilege-escalation/gcp-parallelstore-privesc.md"),
    ("transcoder.*", "gcp-post-exploitation/gcp-transcoder-post-exploitation.md"),
    ("vmmigration.*", "gcp-services/gcp-vm-migration-enum.md"),
    ("vmwareengine.*", "gcp-services/gcp-vmwareengine-gcve-enum.md"),
)
