"""GCP attack-path permissions that supplement the generic risk classifier.

Single-item combinations are intentional: this module is also consumed by
older CloudPEASS integrations. Multi-item combinations model paths that need
all listed permissions before they become critical.
"""


very_sensitive_combinations = [
    # IAM policy changes and principal impersonation.
    ["*.setIamPolicy"],
    ["iam.serviceAccounts.actAs"],
    ["iam.serviceAccounts.getAccessToken"],
    [
        "iam.serviceAccounts.implicitDelegation",
        "iam.serviceAccounts.getAccessToken",
    ],
    ["iam.serviceAccounts.signBlob"],
    ["iam.serviceAccounts.signJwt"],
    ["iam.serviceAccountKeys.create"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.create"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.undelete"],
    ["iam.googleapis.com/workloadIdentityPoolProviders.update"],
    ["iam.googleapis.com/workloadIdentityPools.undelete"],
    ["iam.googleapis.com/workloadIdentityPools.update"],
    ["iam.roles.update"],

    # Credential, secret, and decryption material.
    ["storage.hmacKeys.create"],

    # Direct code execution or supply-chain replacement.
    ["appengine.instances.enableDebug"],
    ["cloudbuild.builds.create"],
    [
        "cloudfunctions.functions.create",
        "cloudfunctions.functions.sourceCodeSet",
        "iam.serviceAccounts.actAs",
    ],
    ["cloudfunctions.functions.update", "iam.serviceAccounts.actAs"],
    ["composer.environments.create", "iam.serviceAccounts.actAs"],
    ["composer.environments.executeAirflowCommand"],
    ["composer.environments.update"],
    ["compute.projects.setCommonInstanceMetadata"],
    ["compute.instances.setMetadata"],
    ["compute.instances.osLogin"],
    ["compute.instances.osAdminLogin"],
    ["osconfig.patchDeployments.create"],
    ["osconfig.patchJobs.exec"],
    ["run.jobs.run", "run.jobs.runWithOverrides"],
    [
        "workflows.workflows.create",
        "iam.serviceAccounts.actAs",
        "workflows.executions.create",
    ],

    # GKE RBAC escalation, secret access, and workload execution.
    ["container.roles.escalate"],
    ["container.clusterRoles.escalate"],
    ["container.roles.bind"],
    ["container.clusterRoles.bind"],
    ["container.cronJobs.create"],
    ["container.cronJobs.update"],
    ["container.daemonSets.create"],
    ["container.daemonSets.update"],
    ["container.deployments.create"],
    ["container.deployments.update"],
    ["container.jobs.create"],
    ["container.jobs.update"],
    ["container.replicaSets.create"],
    ["container.replicaSets.update"],
    ["container.replicationControllers.create"],
    ["container.replicationControllers.update"],
    ["container.scheduledJobs.create"],
    ["container.scheduledJobs.update"],
    ["container.statefulSets.create"],
    ["container.statefulSets.update"],
    ["container.nodes.proxy"],
    ["container.pods.exec"],
    ["container.serviceAccounts.createToken"],
    # Deployment services can execute as more privileged service accounts.
    [
        "dataproc.clusters.get",
        "dataproc.clusters.use",
        "dataproc.jobs.create",
        "dataproc.jobs.get",
        "dataproc.jobs.list",
        "storage.objects.create",
        "storage.objects.get",
    ],
    [
        "dataflow.jobs.create",
        "resourcemanager.projects.get",
        "iam.serviceAccounts.actAs",
    ],
    ["deploymentmanager.deployments.create"],
    ["deploymentmanager.deployments.update"],

    # Database account takeover.
    ["cloudsql.users.create"],
    ["cloudsql.users.update"],

    # Registering a Migration Center discovery client with a caller-specified
    # service account impersonates it (actAs-gated).
    [
        "migrationcenter.discoveryClients.create",
        "iam.serviceAccounts.actAs",
    ],
    # Latest documented permission severity audit.
    ["accesscontextmanager.policies.setIamPolicy"],
    ["analyticshub.dataExchanges.setIamPolicy"],
    ["analyticshub.listings.setIamPolicy"],
    ["apigee.environments.setIamPolicy"],
    ["artifactregistry.repositories.setIamPolicy"],
    ["beyondcorp.sgApplications.setIamPolicy"],
    ["biglake.catalogs.setIamPolicy"],
    ["biglake.namespaces.setIamPolicy"],
    ["biglake.tables.setIamPolicy"],
    ["bigquery.connections.setIamPolicy"],
    ["bigquery.datasets.setIamPolicy"],
    ["bigquery.tables.setIamPolicy"],
    ["bigtable.authorizedViews.setIamPolicy"],
    ["bigtable.backups.setIamPolicy"],
    ["bigtable.instances.setIamPolicy"],
    ["bigtable.materializedViews.setIamPolicy"],
    ["bigtable.tables.setIamPolicy"],
    ["billing.accounts.setIamPolicy"],
    ["binaryauthorization.attestors.setIamPolicy"],
    ["cloudbuild.connections.setIamPolicy"],
    ["cloudkms.cryptoKeys.setIamPolicy"],
    ["cloudtasks.queues.setIamPolicy"],
    ["compute.disks.setIamPolicy"],
    ["compute.instances.setIamPolicy"],
    ["compute.machineImages.setIamPolicy"],
    ["compute.recoverableSnapshots.setIamPolicy"],
    ["compute.snapshots.setIamPolicy"],
    ["connectors.connections.setIamPolicy"],
    ["container.clusters.impersonate"],
    ["containeranalysis.notes.setIamPolicy"],
    ["datacatalog.categories.setIamPolicy"],
    ["datacatalog.taxonomies.setIamPolicy"],
    ["datafusion.instances.setIamPolicy"],
    ["datafusion.namespaces.setIamPolicy"],
    ["dataplex.assets.setIamPolicy"],
    ["dataplex.lakes.setIamPolicy"],
    ["dataplex.zones.setIamPolicy"],
    ["dataproc.clusters.setIamPolicy"],
    ["deploymentmanager.deployments.setIamPolicy"],
    ["discoveryengine.collections.setIamPolicy"],
    ["discoveryengine.dataStores.setIamPolicy"],
    ["discoveryengine.engines.setIamPolicy"],
    ["domains.registrations.setIamPolicy"],
    ["firebaseauth.users.update"],
    ["gkehub.memberships.setIamPolicy"],
    ["healthcare.consentStores.setIamPolicy"],
    ["healthcare.datasets.setIamPolicy"],
    ["healthcare.dicomStores.setIamPolicy"],
    ["healthcare.fhirStores.setIamPolicy"],
    ["healthcare.hl7V2Stores.setIamPolicy"],
    ["iap.tunnelInstances.setIamPolicy"],
    ["iap.tunnelZones.setIamPolicy"],
    ["iap.web.setIamPolicy"],
    ["iap.webServiceVersions.setIamPolicy"],
    ["iap.webServices.setIamPolicy"],
    ["identitytoolkit.tenants.setIamPolicy"],
    ["logging.views.setIamPolicy"],
    ["managedidentities.domains.resetpassword"],
    ["metastore.services.setIamPolicy"],
    ["networkconnectivity.groups.setIamPolicy"],
    ["networkconnectivity.hubs.setIamPolicy"],
    ["networksecurity.addressGroups.setIamPolicy"],
    ["networksecurity.authorizationPolicies.setIamPolicy"],
    ["networksecurity.authzPolicies.setIamPolicy"],
    ["networksecurity.clientTlsPolicies.setIamPolicy"],
    ["networksecurity.serverTlsPolicies.setIamPolicy"],
    ["notebooks.instances.setIamPolicy"],
    ["osconfig.guestPolicies.create"],
    ["osconfig.guestPolicies.update"],
    ["osconfig.osPolicyAssignments.create"],
    ["osconfig.osPolicyAssignments.update"],
    ["osconfig.policyOrchestrators.create"],
    ["privateca.caPools.setIamPolicy"],
    ["pubsub.subscriptions.setIamPolicy"],
    ["pubsub.topics.setIamPolicy"],
    ["resourcemanager.tagKeys.setIamPolicy"],
    ["resourcemanager.tagValues.setIamPolicy"],
    ["run.jobs.setIamPolicy"],
    ["run.services.setIamPolicy"],
    ["runtimeconfig.configs.setIamPolicy"],
    ["secretmanager.secrets.setIamPolicy"],
    ["securesourcemanager.instances.setIamPolicy"],
    ["securesourcemanager.repositories.setIamPolicy"],
    ["securesourcemanager.sshkeys.createAny"],
    ["securitycenter.sources.setIamPolicy"],
    ["servicedirectory.namespaces.setIamPolicy"],
    ["servicedirectory.services.setIamPolicy"],
    ["servicemanagement.services.setIamPolicy"],
    ["source.repos.setIamPolicy"],
    ["spanner.databases.setIamPolicy"],
    ["spanner.instances.setIamPolicy"],
    ["storage.buckets.setIamPolicy"],
    ["storage.managedFolders.setIamPolicy"],
    ["vmwareengine.privateClouds.setIamPolicy"],
    ["workflows.workflows.update"],
    ["workstations.workstations.setIamPolicy"],
]


sensitive_combinations = [
    # Credentials or identity-related changes that usually need more context.
    ["agentidentity.authProviders.retrieveCredentials"],
    ["agentidentity.authProviders.update"],
    ["aiplatform.pipelineJobs.get"],
    ["aiplatform.pipelineJobs.list"],
    ["integrations.integrations.invoke"],
    ["apikeys.keys.create"],
    ["appengine.versions.get"],
    ["appengine.versions.list"],
    ["artifactregistry.repositories.uploadArtifacts"],
    ["iam.serviceAccounts.getOpenIdToken"],
    ["cloudbuild.repositories.accessReadToken"],
    ["cloudbuild.repositories.accessReadWriteToken"],
    ["cloudbuild.builds.get"],
    ["cloudbuild.builds.list"],
    ["cloudscheduler.jobs.get"],
    ["cloudscheduler.jobs.list"],
    ["cloudtasks.tasks.get"],
    ["cloudtasks.tasks.list"],
    ["gsuiteaddons.deployments.update"],
    ["container.clusters.get"],
    ["container.clusters.getCredentials"],
    ["container.pods.attach"],
    ["container.pods.getLogs"],
    ["container.pods.portForward"],
    ["container.pods.proxy"],
    ["container.services.proxy"],
    ["orgpolicy.policy.set"],

    # Direct data access, invocation, or message injection.
    ["artifactregistry.repositories.downloadArtifacts"],
    ["bigquery.tables.getData"],
    ["cloudfunctions.functions.sourceCodeGet"],
    ["cloudsql.instances.connect"],
    ["cloudsql.instances.export"],
    ["cloudsql.instances.executeSql", "cloudsql.instances.login"],
    ["compute.projects.get"],
    ["compute.instanceSettings.get"],
    ["compute.instances.get"],
    ["compute.instances.list"],
    ["compute.instanceTemplates.get"],
    ["compute.instanceTemplates.list"],
    ["compute.machineImages.get"],
    ["compute.machineImages.list"],
    ["compute.instances.getSerialPortOutput"],
    ["datastore.entities.create"],
    ["datastore.entities.delete"],
    ["datastore.entities.get"],
    ["datastore.entities.update"],
    ["dns.changes.create", "dns.resourceRecordSets.create"],
    ["dns.changes.create", "dns.resourceRecordSets.update"],
    ["dns.changes.create", "dns.resourceRecordSets.delete"],
    ["healthcare.dicomStores.dicomWebDelete"],
    ["healthcare.dicomStores.dicomWebRead"],
    ["healthcare.dicomStores.dicomWebWrite"],
    ["healthcare.fhirResources.create"],
    ["healthcare.fhirResources.delete"],
    ["healthcare.fhirResources.get"],
    ["healthcare.fhirResources.patch"],
    ["healthcare.fhirResources.update"],
    ["healthcare.fhirStores.searchResources"],
    ["healthcare.hl7V2Messages.create"],
    ["healthcare.hl7V2Messages.delete"],
    ["healthcare.hl7V2Messages.get"],
    ["healthcare.hl7V2Messages.ingest"],
    ["logging.logEntries.list", "logging.views.access"],
    ["pubsub.subscriptions.consume"],
    ["pubsub.topics.publish"],
    ["redis.instances.getAuthString"],
    ["run.configurations.get"],
    ["run.configurations.list"],
    ["run.executions.get"],
    ["run.executions.list"],
    ["run.jobs.get"],
    ["run.jobs.list"],
    ["run.revisions.get"],
    ["run.revisions.list"],
    ["run.routes.invoke"],
    ["run.services.get"],
    ["run.services.list"],
    ["run.tasks.get"],
    ["run.tasks.list"],
    ["secretmanager.versions.add"],
    ["source.repos.get"],
    ["source.repos.update"],
    ["spanner.databases.read", "spanner.sessions.create"],
    ["spanner.databases.select", "spanner.sessions.create"],
    ["spanner.databases.write", "spanner.sessions.create"],
    ["storage.objects.create"],
    ["storage.objects.delete"],
    ["storage.objects.get"],
    ["workflows.executions.create"],
    ["workflows.executions.get"],
    ["workflows.executions.list"],
    ["workflows.stepEntries.get"],
    ["workflows.stepEntries.list"],
    ["workflows.workflows.get"],
    ["workflows.workflows.list"],

    # Security-control or evidence tampering.
    ["cloudbuild.builds.approve"],
    ["securitycenter.findings.bulkMuteUpdate"],
    # Latest documented permission severity audit.
    ["accessapproval.requests.approve"],
    ["accessapproval.settings.update"],
    ["accesscontextmanager.accessLevels.replaceAll"],
    ["accesscontextmanager.accessLevels.update"],
    ["accesscontextmanager.authorizedOrgsDescs.create"],
    ["accesscontextmanager.gcpUserAccessBindings.create"],
    ["accesscontextmanager.gcpUserAccessBindings.update"],
    ["accesscontextmanager.servicePerimeters.replaceAll"],
    ["accesscontextmanager.servicePerimeters.update"],
    ["advisorynotifications.notifications.list"],
    ["agentregistry.services.update"],
    ["agentregistry.skillRevisions.create"],
    ["agentregistry.skills.update"],
    ["aiplatform.batchPredictionJobs.create"],
    ["aiplatform.customJobs.create"],
    ["aiplatform.datasets.export"],
    ["aiplatform.endpoints.create"],
    ["aiplatform.featureViews.fetchFeatureValues"],
    ["aiplatform.hyperparameterTuningJobs.create"],
    ["aiplatform.models.export"],
    ["aiplatform.models.upload"],
    ["aiplatform.notebookExecutionJobs.create"],
    ["aiplatform.pipelineJobs.create"],
    ["aiplatform.ragCorpora.create"],
    ["aiplatform.ragFiles.import"],
    ["aiplatform.reasoningEngines.create"],
    ["aiplatform.semanticGovernancePolicies.update"],
    ["alloydb.clusters.create"],
    ["alloydb.clusters.export"],
    ["alloydb.clusters.restore"],
    ["alloydb.instances.create"],
    ["alloydb.instances.executeSqlReadOnly"],
    ["alloydb.instances.update"],
    ["alloydb.users.create"],
    ["alloydb.users.update"],
    ["analyticshub.subscriptions.create"],
    ["apigateway.apiconfigs.create"],
    ["apigateway.apis.create"],
    ["apigateway.gateways.create"],
    ["apigateway.gateways.update"],
    ["apigee.deployments.create"],
    ["apigee.flowhooks.attachSharedFlow"],
    ["apigee.proxies.create"],
    ["apigee.sharedflows.create"],
    ["apikeys.keys.getKeyString"],
    ["apikeys.keys.undelete"],
    ["artifactregistry.repositories.create"],
    ["artifactregistry.repositories.exportArtifacts"],
    ["artifactregistry.repositories.update"],
    ["artifactregistry.tags.update"],
    ["backupdr.autoProtectionBindings.create"],
    ["backupdr.autoProtectionPolicies.create"],
    ["backupdr.backupPlans.useForComputeDisk"],
    ["backupdr.backupPlans.useForComputeInstance"],
    ["backupdr.bvbackups.restore"],
    ["backupdr.compute.restoreFromBackupVault"],
    ["beyondcorp.sgApplications.update"],
    ["biglake.tables.getData"],
    ["biglake.tables.update"],
    ["bigquery.dataPolicies.delete"],
    ["bigquery.dataPolicies.update"],
    ["bigquery.datasets.create"],
    ["bigquery.datasets.update"],
    ["bigquery.jobs.create"],
    ["bigquery.jobs.listAll"],
    ["bigquery.models.export"],
    ["bigquery.routines.create"],
    ["bigquery.routines.update"],
    ["bigquery.tables.create"],
    ["bigquery.tables.update"],
    ["bigquery.transfers.update"],
    ["bigtable.authorizedViews.mutateRows"],
    ["bigtable.authorizedViews.update"],
    ["bigtable.backups.restore"],
    ["bigtable.clusters.create"],
    ["bigtable.clusters.update"],
    ["bigtable.tables.create"],
    ["bigtable.tables.update"],
    ["binaryauthorization.attestors.update"],
    ["binaryauthorization.policy.update"],
    ["certificatemanager.certmapentries.create"],
    ["certificatemanager.certmapentries.update"],
    ["certificatemanager.certmaps.create"],
    ["certificatemanager.certmaps.use"],
    ["certificatemanager.certs.create"],
    ["certificatemanager.certs.use"],
    ["certificatemanager.trustconfigs.create"],
    ["certificatemanager.trustconfigs.update"],
    ["certificatemanager.trustconfigs.use"],
    ["ces.agents.update"],
    ["ces.appVersions.create"],
    ["ces.appVersions.restore"],
    ["ces.deployments.update"],
    ["ces.guardrails.update"],
    ["ces.tools.update"],
    ["chronicle.events.searchRawLogs"],
    ["cloudasset.assets.exportIamPolicy"],
    ["cloudasset.assets.exportResource"],
    ["cloudasset.feeds.create"],
    ["clouddeploy.releases.create"],
    ["clouddeploy.releases.get"],
    ["clouddeploy.rollouts.create"],
    ["cloudfunctions.functions.generateUploadUrl"],
    ["cloudkms.autokeyConfigs.update"],
    ["cloudkms.cryptoKeyVersions.update"],
    ["cloudkms.cryptoKeyVersions.useToDecapsulate"],
    ["cloudkms.cryptoKeyVersions.useToDecrypt"],
    ["cloudkms.cryptoKeyVersions.useToDecryptViaDelegation"],
    ["cloudkms.cryptoKeyVersions.useToEncrypt"],
    ["cloudkms.cryptoKeyVersions.useToSign"],
    ["cloudkms.cryptoKeys.create"],
    ["cloudkms.keyHandles.create"],
    ["cloudkms.keyRings.create"],
    ["cloudprivatecatalogproducer.products.update"],
    ["cloudscheduler.jobs.create"],
    ["cloudscheduler.jobs.run"],
    ["cloudscheduler.jobs.update"],
    ["cloudsql.instances.resetSslConfig"],
    ["cloudsql.instances.update"],
    ["cloudsql.sslCerts.create"],
    ["cloudsupport.techCases.list"],
    ["cloudtasks.queues.create"],
    ["cloudtasks.queues.update"],
    ["cloudtasks.tasks.create"],
    ["cloudtasks.tasks.run"],
    ["compute.addresses.use"],
    ["compute.backendBuckets.addSignedUrlKey"],
    ["compute.backendServices.addSignedUrlKey"],
    ["compute.backendServices.create"],
    ["compute.backendServices.setSecurityPolicy"],
    ["compute.backendServices.update"],
    ["compute.backendServices.use"],
    ["compute.disks.createSnapshot"],
    ["compute.disks.useReadOnly"],
    ["compute.firewallPolicies.update"],
    ["compute.images.create"],
    ["compute.images.useReadOnly"],
    ["compute.instanceGroupManagers.create"],
    ["compute.instanceGroupManagers.update"],
    ["compute.instanceTemplates.create"],
    ["compute.instanceTemplates.useReadOnly"],
    ["compute.instances.addAccessConfig"],
    ["compute.instances.attachDisk"],
    ["compute.instances.create"],
    ["compute.instances.createTagBinding"],
    ["compute.instances.getGuestAttributes"],
    ["compute.instances.updateNetworkInterface"],
    ["compute.instances.updateSecurity"],
    ["compute.instances.updateShieldedInstanceConfig"],
    ["compute.machineImages.useReadOnly"],
    ["compute.networks.access"],
    ["compute.networks.updatePolicy"],
    ["compute.networks.use"],
    ["compute.oslogin.updateExternalUser"],
    ["compute.packetMirrorings.create"],
    ["compute.routers.create"],
    ["compute.routers.update"],
    ["compute.routes.create"],
    ["compute.securityPolicies.update"],
    ["compute.securityPolicies.use"],
    ["compute.snapshots.create"],
    ["compute.snapshots.useReadOnly"],
    ["compute.subnetworks.update"],
    ["compute.subnetworks.use"],
    ["compute.subnetworks.useExternalIp"],
    ["compute.targetHttpsProxies.update"],
    ["compute.targetSslProxies.update"],
    ["compute.urlMaps.update"],
    ["config.deployments.create"],
    ["configdelivery.fleetPackages.update"],
    ["connectors.actions.execute"],
    ["connectors.connections.executeSqlQuery"],
    ["contactcenterinsights.conversations.generateSignedAudio"],
    ["container.clusterRoleBindings.create"],
    ["container.clusters.create"],
    ["container.clusters.update"],
    ["container.mutatingWebhookConfigurations.create"],
    ["container.mutatingWebhookConfigurations.update"],
    ["container.nodePools.create"],
    ["container.nodePools.update"],
    ["container.pods.create"],
    ["container.pods.update"],
    ["container.roleBindings.create"],
    ["container.secrets.get"],
    ["container.secrets.list"],
    ["containeranalysis.notes.attachOccurrence"],
    ["containeranalysis.occurrences.create"],
    ["datacatalog.taxonomies.update"],
    ["dataform.compilationResults.create"],
    ["dataform.repositories.create"],
    ["dataform.workflowInvocations.create"],
    ["dataform.workspaces.create"],
    ["dataform.workspaces.writeFile"],
    ["datafusion.artifacts.create"],
    ["datafusion.artifacts.update"],
    ["datafusion.pipelineConnections.use"],
    ["datafusion.pipelines.create"],
    ["datafusion.pipelines.execute"],
    ["datafusion.secureKeys.getSecret"],
    ["datapipelines.pipelines.create"],
    ["dataplex.tasks.create"],
    ["dataproc.batches.create"],
    ["dataproc.clusters.create"],
    ["dataproc.sessionTemplates.create"],
    ["dataproc.sessions.create"],
    ["dataproc.workflowTemplates.create"],
    ["datastore.databases.export"],
    ["datastore.userCreds.create"],
    ["datastore.userCreds.update"],
    ["datastream.connectionProfiles.create"],
    ["datastream.objects.startBackfillJob"],
    ["datastream.privateConnections.create"],
    ["datastream.routes.create"],
    ["datastream.streams.create"],
    ["datastream.streams.update"],
    ["deploymentmanager.manifests.get"],
    ["developerconnect.gitRepositoryLinks.fetchReadToken"],
    ["developerconnect.gitRepositoryLinks.fetchReadWriteToken"],
    ["dialogflow.webhooks.update"],
    ["discoveryengine.identityMappingStores.importIdentityMappings"],
    ["dlp.contentPolicies.update"],
    ["dlp.deidentifyTemplates.get"],
    ["dlp.deidentifyTemplates.update"],
    ["dlp.jobTriggers.create"],
    ["dlp.jobs.create"],
    ["dns.gkeClusters.bindDNSResponsePolicy"],
    ["dns.gkeClusters.bindPrivateDNSZone"],
    ["dns.managedZones.create"],
    ["dns.networks.bindDNSResponsePolicy"],
    ["dns.networks.bindPrivateDNSPolicy"],
    ["dns.networks.bindPrivateDNSZone"],
    ["dns.policies.create"],
    ["dns.policies.update"],
    ["dns.responsePolicies.create"],
    ["dns.responsePolicyRules.create"],
    ["documentai.datasets.getDocuments"],
    ["documentai.datasets.listDocuments"],
    ["documentai.processorVersions.create"],
    ["essentialcontacts.contacts.create"],
    ["eventarc.enrollments.update"],
    ["eventarc.pipelines.create"],
    ["eventarc.triggers.create"],
    ["eventarc.triggers.update"],
    ["file.backups.create"],
    ["file.backups.useReadOnly"],
    ["file.instances.create"],
    ["file.instances.update"],
    ["firebaseapphosting.backends.update"],
    ["firebaseapphosting.builds.create"],
    ["firebaseapphosting.rollouts.create"],
    ["firebaseauth.configs.update"],
    ["firebaserules.releases.create"],
    ["firebaserules.releases.update"],
    ["firebaserules.rulesets.create"],
    ["gkebackup.backupPlans.create"],
    ["gkebackup.backups.create"],
    ["gkebackup.restorePlans.create"],
    ["gkebackup.restores.create"],
    ["gkehub.features.create"],
    ["gkehub.gateway.generateCredentials"],
    ["gkehub.membershipfeatures.update"],
    ["gkehub.rbacrolebindings.create"],
    ["healthcare.datasets.create"],
    ["healthcare.dicomStores.export"],
    ["healthcare.fhirStores.export"],
    ["healthcare.fhirStores.update"],
    ["healthcare.hl7V2Stores.export"],
    ["hypercomputecluster.clusters.update"],
    ["iam.serviceAccounts.undelete"],
    ["iap.tunnelInstances.accessViaIAP"],
    ["iap.web.updateSettings"],
    ["integrations.authConfigs.get"],
    ["livestream.channels.get"],
    ["livestream.channels.start"],
    ["livestream.events.create"],
    ["livestream.inputs.create"],
    ["logging.links.create"],
    ["logging.notificationRules.create"],
    ["logging.sinks.create"],
    ["logging.sinks.update"],
    ["logging.views.create"],
    ["managedflink.deployments.create"],
    ["managedflink.jobs.create"],
    ["managedkafka.acls.create"],
    ["mcp.tools.call"],
    ["modelarmor.floorSettings.update"],
    ["modelarmor.templates.update"],
    ["monitoring.alertPolicies.create"],
    ["monitoring.notificationChannels.create"],
    ["monitoring.notificationChannels.update"],
    ["monitoring.uptimeCheckConfigs.create"],
    ["netapp.backups.useReadOnly"],
    ["netapp.volumes.create"],
    ["networkconnectivity.hubs.create"],
    ["networkconnectivity.hubs.use"],
    ["networkconnectivity.policyBasedRoutes.create"],
    ["networkconnectivity.spokes.create"],
    ["networksecurity.addressGroups.update"],
    ["networksecurity.authorizationPolicies.update"],
    ["networksecurity.authzPolicies.create"],
    ["networksecurity.authzPolicies.update"],
    ["networksecurity.interceptDeploymentGroups.use"],
    ["networksecurity.interceptDeployments.create"],
    ["networksecurity.interceptEndpointGroupAssociations.create"],
    ["networksecurity.interceptEndpointGroups.create"],
    ["networksecurity.interceptEndpointGroups.use"],
    ["networksecurity.mirroringDeploymentGroups.use"],
    ["networksecurity.mirroringEndpointGroupAssociations.create"],
    ["networksecurity.mirroringEndpointGroups.create"],
    ["networksecurity.mirroringEndpointGroups.use"],
    ["networksecurity.securityProfileGroups.create"],
    ["networksecurity.securityProfileGroups.use"],
    ["networksecurity.securityProfiles.create"],
    ["networksecurity.securityProfiles.update"],
    ["networksecurity.securityProfiles.use"],
    ["networksecurity.serverTlsPolicies.use"],
    ["networkservices.authzExtensions.create"],
    ["networkservices.authzExtensions.use"],
    ["networkservices.googleTagGatewayPolicies.create"],
    ["networkservices.lbTrafficExtensions.create"],
    ["networkservices.meshes.use"],
    ["networkservices.wasmPlugins.create"],
    ["notebooks.instances.create"],
    ["notebooks.instances.reset"],
    ["notebooks.instances.update"],
    ["notebooks.instances.use"],
    ["observability.links.create"],
    ["observability.views.access"],
    ["oracledatabase.autonomousDatabases.generateWallet"],
    ["orgpolicy.customConstraints.create"],
    ["orgpolicy.customConstraints.update"],
    ["orgpolicy.policies.create"],
    ["orgpolicy.policies.delete"],
    ["orgpolicy.policies.update"],
    ["osconfig.patchDeployments.update"],
    ["privateca.caPools.update"],
    ["privateca.certificateAuthorities.create"],
    ["privateca.certificateAuthorities.update"],
    ["privateca.certificateTemplates.update"],
    ["privateca.certificateTemplates.use"],
    ["privateca.certificates.create"],
    ["privateca.certificates.createForSelf"],
    ["pubsub.subscriptions.create"],
    ["pubsub.subscriptions.update"],
    ["pubsub.topics.attachSubscription"],
    ["recaptchaenterprise.firewallpolicies.create"],
    ["recaptchaenterprise.firewallpolicies.update"],
    ["recaptchaenterprise.keys.retrievelegacysecretkey"],
    ["recaptchaenterprise.keys.update"],
    ["recaptchaenterprise.policies.update"],
    ["redis.clusters.connect"],
    ["redis.instances.export"],
    ["resourcemanager.folders.move"],
    ["resourcemanager.hierarchyNodes.createTagBinding"],
    ["resourcemanager.projects.deletePolicyBinding"],
    ["resourcemanager.projects.move"],
    ["resourcemanager.projects.update"],
    ["resourcemanager.projects.updatePolicyBinding"],
    ["resourcemanager.tagValueBindings.create"],
    ["run.jobs.create"],
    ["run.jobs.update"],
    ["run.locations.exportImage"],
    ["run.services.create"],
    ["run.services.update"],
    ["run.workerpools.create"],
    ["run.workerpools.update"],
    ["runtimeconfig.variables.get"],
    ["saasservicemgmt.releases.create"],
    ["secretmanager.secrets.enableManagedRotation"],
    ["secretmanager.secrets.update"],
    ["secretmanager.versions.access"],
    ["securesourcemanager.branchRules.create"],
    ["securesourcemanager.hooks.create"],
    ["securesourcemanager.repositories.approvePullRequests"],
    ["securesourcemanager.repositories.fetch"],
    ["securesourcemanager.repositories.readPullRequests"],
    ["servicedirectory.endpoints.create"],
    ["servicedirectory.endpoints.update"],
    ["servicedirectory.networks.attach"],
    ["servicemanagement.services.update"],
    ["serviceusage.services.use"],
    ["spanner.backups.create"],
    ["spanner.backups.restoreDatabase"],
    ["spanner.databases.create"],
    ["spanner.databases.createBackup"],
    ["spanner.databases.updateDdl"],
    ["storage.buckets.create"],
    ["storage.buckets.delete"],
    ["storage.buckets.restore"],
    ["storage.buckets.update"],
    ["storagetransfer.jobs.create"],
    ["storagetransfer.jobs.run"],
    ["storagetransfer.jobs.update"],
    ["vmmigration.imageImports.create"],
    ["vmmigration.migratingVms.create"],
    ["vpcaccess.connectors.create"],
    ["workstations.workstationConfigs.create"],
]


# Every Critical/High exact permission or combination above must match one of
# these evidence families. The referenced HackTricks Cloud page contains the
# concrete abuse or data-access procedure; tests prevent adding an unreferenced
# high-severity permission by accident.
risk_documentation = (
    (
        "agentidentity.authProviders.retrieveCredentials",
        "gcp-to-workspace-pivoting/gcp-agent-identity-auth-manager-privesc.md",
    ),
    (
        "agentidentity.authProviders.update",
        "gcp-to-workspace-pivoting/gcp-agent-identity-auth-manager-privesc.md",
    ),
    (
        "aiplatform.pipelineJobs.get",
        "gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md",
    ),
    (
        "aiplatform.pipelineJobs.list",
        "gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md",
    ),
    (
        "iam.serviceAccounts.getAccessToken",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "iam.serviceAccounts.signBlob",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "iam.serviceAccounts.signJwt",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "resourcemanager.organizations.setIamPolicy",
        "gcp-to-workspace-pivoting/README.md",
    ),
    (
        "gsuiteaddons.deployments.update",
        "gcp-to-workspace-pivoting/gcp-workspace-addons-privesc.md",
    ),
    (
        "integrations.integrations.invoke",
        "gcp-to-workspace-pivoting/gcp-application-integration-privesc.md",
    ),
    (
        "integrations.authConfigs.get",
        "gcp-to-workspace-pivoting/gcp-application-integration-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.create",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.undelete",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPoolProviders.update",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPools.undelete",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    (
        "iam.googleapis.com/workloadIdentityPools.update",
        "gcp-privilege-escalation/gcp-workload-identity-federation-privesc.md",
    ),
    ("*.setIamPolicy", "gcp-privilege-escalation/gcp-misc-perms-privesc.md"),
    ("cloudbuild.builds.approve", "gcp-post-exploitation/gcp-cloud-build-post-exploitation.md"),
    ("cloudfunctions.functions.sourceCodeGet", "gcp-post-exploitation/gcp-cloud-functions-post-exploitation.md"),
    ("cloudkms.cryptoKeyVersions.destroy", "gcp-post-exploitation/gcp-kms-post-exploitation.md"),
    ("dataflow.jobs.create", "gcp-post-exploitation/gcp-dataflow-post-exploitation.md"),
    ("logging.views.access", "gcp-post-exploitation/gcp-app-engine-post-exploitation.md"),
    ("pubsub.topics.publish", "gcp-post-exploitation/gcp-pub-sub-post-exploitation.md"),
    ("resourcemanager.projects.get", "gcp-post-exploitation/gcp-dataflow-post-exploitation.md"),
    ("apikeys.*", "gcp-privilege-escalation/gcp-serviceusage-privesc.md"),
    (
        "appengine.versions.get",
        "gcp-post-exploitation/gcp-app-engine-post-exploitation.md",
    ),
    (
        "appengine.versions.list",
        "gcp-post-exploitation/gcp-app-engine-post-exploitation.md",
    ),
    ("appengine.*", "gcp-privilege-escalation/gcp-appengine-privesc.md"),
    ("artifactregistry.*", "gcp-privilege-escalation/gcp-artifact-registry-privesc.md"),
    ("bigquery.*", "gcp-privilege-escalation/gcp-bigquery-privesc.md"),
    ("bigtable.*", "gcp-post-exploitation/gcp-bigtable-post-exploitation.md"),
    ("clientauthconfig.*", "gcp-privilege-escalation/gcp-clientauthconfig-privesc.md"),
    ("cloudbuild.*", "gcp-privilege-escalation/gcp-cloudbuild-privesc.md"),
    ("cloudscheduler.*", "gcp-privilege-escalation/gcp-cloudscheduler-privesc.md"),
    ("cloudtasks.*", "gcp-privilege-escalation/gcp-cloudtasks-privesc.md"),
    ("cloudfunctions.*", "gcp-privilege-escalation/gcp-cloudfunctions-privesc.md"),
    ("cloudkms.*", "gcp-privilege-escalation/gcp-kms-privesc.md"),
    ("cloudsql.*", "gcp-post-exploitation/gcp-cloud-sql-post-exploitation.md"),
    ("composer.*", "gcp-privilege-escalation/gcp-composer-privesc.md"),
    (
        "compute.instances.getSerialPortOutput",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.projects.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceSettings.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instances.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instances.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceTemplates.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.instanceTemplates.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.machineImages.get",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    (
        "compute.machineImages.list",
        "gcp-post-exploitation/gcp-compute-post-exploitation.md",
    ),
    ("compute.*", "gcp-privilege-escalation/gcp-compute-privesc/README.md"),
    ("container.*", "gcp-privilege-escalation/gcp-container-privesc.md"),
    ("datastore.*", "gcp-privilege-escalation/gcp-firebase-privesc.md"),
    ("dataflow.*", "gcp-privilege-escalation/gcp-dataflow-privesc.md"),
    ("dataproc.*", "gcp-privilege-escalation/gcp-dataproc-privesc.md"),
    ("deploymentmanager.*", "gcp-privilege-escalation/gcp-deploymentmaneger-privesc.md"),
    ("dns.*", "gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md"),
    ("iam.*", "gcp-privilege-escalation/gcp-iam-privesc.md"),
    ("healthcare.*", "gcp-post-exploitation/gcp-healthcare-post-exploitation.md"),
    ("logging.*", "gcp-post-exploitation/gcp-logging-post-exploitation.md"),
    ("monitoring.*", "gcp-post-exploitation/gcp-monitoring-post-exploitation.md"),
    ("orgpolicy.*", "gcp-privilege-escalation/gcp-orgpolicy-privesc.md"),
    ("osconfig.*", "gcp-privilege-escalation/gcp-compute-privesc/README.md"),
    ("pubsub.*", "gcp-privilege-escalation/gcp-pubsub-privesc.md"),
    ("redis.*", "gcp-post-exploitation/gcp-memorystore-post-exploitation.md"),
    ("resourcemanager.*", "gcp-privilege-escalation/gcp-resourcemanager-privesc.md"),
    ("run.*", "gcp-privilege-escalation/gcp-run-privesc.md"),
    ("secretmanager.*", "gcp-privilege-escalation/gcp-secretmanager-privesc.md"),
    ("securitycenter.*", "gcp-post-exploitation/gcp-security-post-exploitation.md"),
    ("source.*", "gcp-privilege-escalation/gcp-sourcerepos-privesc.md"),
    ("spanner.*", "gcp-post-exploitation/gcp-spanner-post-exploitation.md"),
    ("storage.*", "gcp-privilege-escalation/gcp-storage-privesc.md"),
    ("workflows.*", "gcp-privilege-escalation/gcp-workflows-privesc.md"),
    # Newer service attack paths. Some are documented on the service enum pages
    # under gcp-services/ rather than a dedicated privesc/post-exploitation page.
    ("baremetalsolution.*", "gcp-services/gcp-bare-metal-solution-enum.md"),
    ("biglake.*", "gcp-services/gcp-biglake-enum.md"),
    ("cloudtrace.*", "gcp-services/gcp-trace-profiler-error-reporting-enum.md"),
    ("contactcenterinsights.*", "gcp-services/gcp-contact-center-insights-enum.md"),
    ("discoveryengine.*", "gcp-services/gcp-vertex-ai-search-enum.md"),
    ("domains.*", "gcp-post-exploitation/gcp-cloud-domains-post-exploitation.md"),
    ("errorreporting.*", "gcp-services/gcp-trace-profiler-error-reporting-enum.md"),
    ("krmapihosting.*", "gcp-services/gcp-config-controller-enum.md"),
    ("livestream.*", "gcp-post-exploitation/gcp-live-stream-post-exploitation.md"),
    ("looker.*", "gcp-services/gcp-looker-enum.md"),
    ("managedkafka.*", "gcp-services/gcp-managed-kafka-enum.md"),
    ("migrationcenter.*", "gcp-services/gcp-migration-center-enum.md"),
    ("netapp.*", "gcp-services/gcp-netapp-volumes-enum.md"),
    ("networksecurity.*", "gcp-privilege-escalation/gcp-networksecurity-privesc.md"),
    ("networkservices.*", "gcp-privilege-escalation/gcp-networkservices-privesc.md"),
    ("parallelstore.*", "gcp-privilege-escalation/gcp-parallelstore-privesc.md"),
    ("transcoder.*", "gcp-post-exploitation/gcp-transcoder-post-exploitation.md"),
    ("vmmigration.*", "gcp-services/gcp-vm-migration-enum.md"),
    ("vmwareengine.*", "gcp-services/gcp-vmwareengine-gcve-enum.md"),
)

# Exact evidence for additions from the latest master audit.
risk_documentation += (
    ('accessapproval.requests.approve', 'gcp-post-exploitation/gcp-access-approval-post-exploitation.md'),
    ('accessapproval.settings.update', 'gcp-post-exploitation/gcp-access-approval-post-exploitation.md'),
    ('accesscontextmanager.accessLevels.replaceAll', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.accessLevels.update', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.authorizedOrgsDescs.create', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.gcpUserAccessBindings.create', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.gcpUserAccessBindings.update', 'gcp-persistence/gcp-vpc-service-controls-persistence.md'),
    ('accesscontextmanager.policies.setIamPolicy', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.servicePerimeters.replaceAll', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('accesscontextmanager.servicePerimeters.update', 'gcp-privilege-escalation/gcp-access-context-manager-privesc.md'),
    ('advisorynotifications.notifications.list', 'gcp-post-exploitation/gcp-advisory-notifications-post-exploitation.md'),
    ('agentregistry.services.update', 'gcp-privilege-escalation/gcp-agent-registry-privesc.md'),
    ('agentregistry.skillRevisions.create', 'gcp-privilege-escalation/gcp-agent-registry-privesc.md'),
    ('agentregistry.skills.update', 'gcp-privilege-escalation/gcp-agent-registry-privesc.md'),
    ('aiplatform.batchPredictionJobs.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.customJobs.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.datasets.export', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('aiplatform.endpoints.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.featureViews.fetchFeatureValues', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('aiplatform.hyperparameterTuningJobs.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.models.export', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('aiplatform.models.upload', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.notebookExecutionJobs.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.pipelineJobs.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.ragCorpora.create', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('aiplatform.ragFiles.import', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('aiplatform.reasoningEngines.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('aiplatform.semanticGovernancePolicies.update', 'gcp-post-exploitation/gcp-vertex-ai-post-exploitation.md'),
    ('alloydb.clusters.create', 'gcp-post-exploitation/gcp-alloydb-post-exploitation.md'),
    ('alloydb.clusters.export', 'gcp-post-exploitation/gcp-alloydb-post-exploitation.md'),
    ('alloydb.clusters.restore', 'gcp-post-exploitation/gcp-alloydb-post-exploitation.md'),
    ('alloydb.instances.create', 'gcp-post-exploitation/gcp-alloydb-post-exploitation.md'),
    ('alloydb.instances.executeSqlReadOnly', 'gcp-post-exploitation/gcp-alloydb-post-exploitation.md'),
    ('alloydb.instances.update', 'gcp-persistence/gcp-alloydb-persistence.md'),
    ('alloydb.users.create', 'gcp-persistence/gcp-alloydb-persistence.md'),
    ('alloydb.users.update', 'gcp-persistence/gcp-alloydb-persistence.md'),
    ('analyticshub.dataExchanges.setIamPolicy', 'gcp-privilege-escalation/gcp-analytics-hub-privesc.md'),
    ('analyticshub.listings.setIamPolicy', 'gcp-privilege-escalation/gcp-analytics-hub-privesc.md'),
    ('analyticshub.subscriptions.create', 'gcp-privilege-escalation/gcp-analytics-hub-privesc.md'),
    ('apigateway.apiconfigs.create', 'gcp-post-exploitation/gcp-api-gateway-post-exploitation.md'),
    ('apigateway.apis.create', 'gcp-post-exploitation/gcp-api-gateway-post-exploitation.md'),
    ('apigateway.gateways.create', 'gcp-post-exploitation/gcp-api-gateway-post-exploitation.md'),
    ('apigateway.gateways.update', 'gcp-post-exploitation/gcp-api-gateway-post-exploitation.md'),
    ('apigee.deployments.create', 'gcp-privilege-escalation/gcp-apigee-privesc.md'),
    ('apigee.environments.setIamPolicy', 'gcp-persistence/gcp-apigee-persistence.md'),
    ('apigee.flowhooks.attachSharedFlow', 'gcp-privilege-escalation/gcp-apigee-privesc.md'),
    ('apigee.proxies.create', 'gcp-privilege-escalation/gcp-apigee-privesc.md'),
    ('apigee.sharedflows.create', 'gcp-privilege-escalation/gcp-apigee-privesc.md'),
    ('apikeys.keys.getKeyString', 'gcp-persistence/gcp-api-keys-persistence.md'),
    ('apikeys.keys.undelete', 'gcp-persistence/gcp-api-keys-persistence.md'),
    ('artifactregistry.repositories.create', 'gcp-persistence/gcp-artifact-registry-persistence.md'),
    ('artifactregistry.repositories.exportArtifacts', 'gcp-post-exploitation/gcp-artifact-registry-post-exploitation.md'),
    ('artifactregistry.repositories.setIamPolicy', 'gcp-post-exploitation/gcp-artifact-registry-post-exploitation.md'),
    ('artifactregistry.repositories.update', 'gcp-persistence/gcp-artifact-registry-persistence.md'),
    ('artifactregistry.tags.update', 'gcp-privilege-escalation/gcp-artifact-registry-privesc.md'),
    ('backupdr.autoProtectionBindings.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('backupdr.autoProtectionPolicies.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('backupdr.backupPlans.useForComputeDisk', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('backupdr.backupPlans.useForComputeInstance', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('backupdr.bvbackups.restore', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('backupdr.compute.restoreFromBackupVault', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('beyondcorp.sgApplications.setIamPolicy', 'gcp-privilege-escalation/gcp-beyondcorp-privesc.md'),
    ('beyondcorp.sgApplications.update', 'gcp-privilege-escalation/gcp-beyondcorp-privesc.md'),
    ('biglake.catalogs.setIamPolicy', 'gcp-persistence/gcp-biglake-persistence.md'),
    ('biglake.namespaces.setIamPolicy', 'gcp-persistence/gcp-biglake-persistence.md'),
    ('biglake.tables.getData', 'gcp-post-exploitation/gcp-biglake-post-exploitation.md'),
    ('biglake.tables.setIamPolicy', 'gcp-persistence/gcp-biglake-persistence.md'),
    ('biglake.tables.update', 'gcp-post-exploitation/gcp-biglake-post-exploitation.md'),
    ('bigquery.connections.setIamPolicy', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.dataPolicies.delete', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.dataPolicies.update', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.datasets.create', 'gcp-privilege-escalation/gcp-analytics-hub-privesc.md'),
    ('bigquery.datasets.setIamPolicy', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigquery.datasets.update', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigquery.jobs.create', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigquery.jobs.listAll', 'gcp-post-exploitation/gcp-bigquery-post-exploitation.md'),
    ('bigquery.models.export', 'gcp-post-exploitation/gcp-bigquery-post-exploitation.md'),
    ('bigquery.routines.create', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.routines.update', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.tables.create', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigquery.tables.setIamPolicy', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('bigquery.tables.update', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigquery.transfers.update', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('bigtable.authorizedViews.mutateRows', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.authorizedViews.setIamPolicy', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.authorizedViews.update', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.backups.restore', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.backups.setIamPolicy', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.clusters.create', 'gcp-persistence/gcp-bigtable-persistence.md'),
    ('bigtable.clusters.update', 'gcp-persistence/gcp-bigtable-persistence.md'),
    ('bigtable.instances.setIamPolicy', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.materializedViews.setIamPolicy', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.tables.create', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.tables.setIamPolicy', 'gcp-privilege-escalation/gcp-bigtable-privesc.md'),
    ('bigtable.tables.update', 'gcp-persistence/gcp-bigtable-persistence.md'),
    ('billing.accounts.setIamPolicy', 'gcp-privilege-escalation/gcp-billing-privesc.md'),
    ('binaryauthorization.attestors.setIamPolicy', 'gcp-persistence/gcp-container-analysis-persistence.md'),
    ('binaryauthorization.attestors.update', 'gcp-post-exploitation/gcp-binary-authorization-post-exploitation.md'),
    ('binaryauthorization.policy.update', 'gcp-post-exploitation/gcp-binary-authorization-post-exploitation.md'),
    ('certificatemanager.certmapentries.create', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.certmapentries.update', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.certmaps.create', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.certmaps.use', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.certs.create', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.certs.use', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.trustconfigs.create', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.trustconfigs.update', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('certificatemanager.trustconfigs.use', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('ces.agents.update', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('ces.appVersions.create', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('ces.appVersions.restore', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('ces.deployments.update', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('ces.guardrails.update', 'gcp-post-exploitation/gcp-cx-agent-studio-post-exploitation.md'),
    ('ces.tools.update', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('chronicle.events.searchRawLogs', 'gcp-post-exploitation/gcp-google-secops-post-exploitation.md'),
    ('cloudasset.assets.exportIamPolicy', 'gcp-post-exploitation/gcp-cloud-asset-inventory-post-exploitation.md'),
    ('cloudasset.assets.exportResource', 'gcp-post-exploitation/gcp-cloud-asset-inventory-post-exploitation.md'),
    ('cloudasset.feeds.create', 'gcp-persistence/gcp-cloud-asset-inventory-persistence.md'),
    ('cloudbuild.connections.setIamPolicy', 'gcp-privilege-escalation/gcp-cloudbuild-privesc.md'),
    ('clouddeploy.releases.create', 'gcp-privilege-escalation/gcp-cloud-deploy-privesc.md'),
    ('clouddeploy.releases.get', 'gcp-post-exploitation/gcp-cloud-deploy-post-exploitation.md'),
    ('clouddeploy.rollouts.create', 'gcp-privilege-escalation/gcp-cloud-deploy-privesc.md'),
    ('cloudfunctions.functions.generateUploadUrl', 'gcp-privilege-escalation/gcp-cloudfunctions-privesc.md'),
    ('cloudkms.autokeyConfigs.update', 'gcp-privilege-escalation/gcp-kms-privesc.md'),
    ('cloudkms.cryptoKeyVersions.update', 'gcp-privilege-escalation/gcp-kms-privesc.md'),
    ('cloudkms.cryptoKeyVersions.useToDecapsulate', 'gcp-post-exploitation/gcp-kms-post-exploitation.md'),
    ('cloudkms.cryptoKeyVersions.useToDecrypt', 'gcp-post-exploitation/gcp-dlp-post-exploitation.md'),
    ('cloudkms.cryptoKeyVersions.useToDecryptViaDelegation', 'gcp-privilege-escalation/gcp-kms-privesc.md'),
    ('cloudkms.cryptoKeyVersions.useToEncrypt', 'gcp-post-exploitation/gcp-looker-post-exploitation.md'),
    ('cloudkms.cryptoKeyVersions.useToSign', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('cloudkms.cryptoKeys.create', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('cloudkms.cryptoKeys.setIamPolicy', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('cloudkms.keyHandles.create', 'gcp-privilege-escalation/gcp-kms-privesc.md'),
    ('cloudkms.keyRings.create', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('cloudprivatecatalogproducer.products.update', 'gcp-privilege-escalation/gcp-private-catalog-privesc.md'),
    ('cloudscheduler.jobs.create', 'gcp-persistence/gcp-cloud-scheduler-persistence.md'),
    ('cloudscheduler.jobs.run', 'gcp-privilege-escalation/gcp-cloudscheduler-privesc.md'),
    ('cloudscheduler.jobs.update', 'gcp-persistence/gcp-cloud-scheduler-persistence.md'),
    ('cloudsql.instances.resetSslConfig', 'gcp-post-exploitation/gcp-cloud-sql-post-exploitation.md'),
    ('cloudsql.instances.update', 'gcp-persistence/gcp-cloud-sql-persistence.md'),
    ('cloudsql.sslCerts.create', 'gcp-persistence/gcp-cloud-sql-persistence.md'),
    ('cloudsql.users.update', 'gcp-persistence/gcp-cloud-sql-persistence.md'),
    ('cloudsupport.techCases.list', 'gcp-post-exploitation/gcp-cloud-support-post-exploitation.md'),
    ('cloudtasks.queues.create', 'gcp-persistence/gcp-cloud-tasks-persistence.md'),
    ('cloudtasks.queues.setIamPolicy', 'gcp-privilege-escalation/gcp-cloudtasks-privesc.md'),
    ('cloudtasks.queues.update', 'gcp-persistence/gcp-cloud-tasks-persistence.md'),
    ('cloudtasks.tasks.create', 'gcp-persistence/gcp-cloud-tasks-persistence.md'),
    ('cloudtasks.tasks.run', 'gcp-privilege-escalation/gcp-cloudtasks-privesc.md'),
    ('compute.addresses.use', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.backendBuckets.addSignedUrlKey', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.backendServices.addSignedUrlKey', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.backendServices.create', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('compute.backendServices.setSecurityPolicy', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.backendServices.update', 'gcp-privilege-escalation/gcp-iap-privesc.md'),
    ('compute.backendServices.use', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.disks.createSnapshot', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.disks.setIamPolicy', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.disks.useReadOnly', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.firewallPolicies.update', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('compute.images.create', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.images.useReadOnly', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.instanceGroupManagers.create', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.instanceGroupManagers.update', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.instanceTemplates.create', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.instanceTemplates.useReadOnly', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.instances.addAccessConfig', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.instances.attachDisk', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.instances.create', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.instances.createTagBinding', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('compute.instances.getGuestAttributes', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.instances.setIamPolicy', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.instances.updateNetworkInterface', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.instances.updateSecurity', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.instances.updateShieldedInstanceConfig', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.machineImages.setIamPolicy', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.machineImages.useReadOnly', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.networks.access', 'gcp-post-exploitation/gcp-cloud-run-post-exploitation.md'),
    ('compute.networks.updatePolicy', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.networks.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('compute.oslogin.updateExternalUser', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.packetMirrorings.create', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.recoverableSnapshots.setIamPolicy', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.routers.create', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.routers.update', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.routes.create', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.securityPolicies.update', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.securityPolicies.use', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.snapshots.create', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.snapshots.setIamPolicy', 'gcp-privilege-escalation/gcp-compute-privesc/README.md'),
    ('compute.snapshots.useReadOnly', 'gcp-persistence/gcp-compute-persistence.md'),
    ('compute.subnetworks.update', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.subnetworks.use', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.subnetworks.useExternalIp', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('compute.targetHttpsProxies.update', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('compute.targetSslProxies.update', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('compute.urlMaps.update', 'gcp-post-exploitation/gcp-compute-post-exploitation.md'),
    ('config.deployments.create', 'gcp-privilege-escalation/gcp-infra-manager-privesc.md'),
    ('configdelivery.fleetPackages.update', 'gcp-privilege-escalation/gcp-config-delivery-privesc.md'),
    ('connectors.actions.execute', 'gcp-post-exploitation/gcp-integration-connectors-post-exploitation.md'),
    ('connectors.connections.executeSqlQuery', 'gcp-post-exploitation/gcp-integration-connectors-post-exploitation.md'),
    ('connectors.connections.setIamPolicy', 'gcp-privilege-escalation/gcp-integration-connectors-privesc.md'),
    ('contactcenterinsights.conversations.generateSignedAudio', 'gcp-post-exploitation/gcp-contact-center-insights-post-exploitation.md'),
    ('container.clusterRoleBindings.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.clusterRoles.bind', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.clusterRoles.escalate', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.clusters.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.clusters.impersonate', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.clusters.update', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.mutatingWebhookConfigurations.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.mutatingWebhookConfigurations.update', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.nodePools.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.nodePools.update', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.pods.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.pods.update', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.roleBindings.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.roles.bind', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.roles.escalate', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.secrets.get', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('container.secrets.list', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('containeranalysis.notes.attachOccurrence', 'gcp-post-exploitation/gcp-binary-authorization-post-exploitation.md'),
    ('containeranalysis.notes.setIamPolicy', 'gcp-persistence/gcp-container-analysis-persistence.md'),
    ('containeranalysis.occurrences.create', 'gcp-post-exploitation/gcp-binary-authorization-post-exploitation.md'),
    ('datacatalog.categories.setIamPolicy', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('datacatalog.taxonomies.setIamPolicy', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('datacatalog.taxonomies.update', 'gcp-privilege-escalation/gcp-bigquery-privesc.md'),
    ('dataform.compilationResults.create', 'gcp-privilege-escalation/gcp-dataform-privesc.md'),
    ('dataform.repositories.create', 'gcp-privilege-escalation/gcp-dataform-privesc.md'),
    ('dataform.workflowInvocations.create', 'gcp-privilege-escalation/gcp-dataform-privesc.md'),
    ('dataform.workspaces.create', 'gcp-privilege-escalation/gcp-dataform-privesc.md'),
    ('dataform.workspaces.writeFile', 'gcp-privilege-escalation/gcp-dataform-privesc.md'),
    ('datafusion.artifacts.create', 'gcp-persistence/gcp-data-fusion-persistence.md'),
    ('datafusion.artifacts.update', 'gcp-privilege-escalation/gcp-data-fusion-privesc.md'),
    ('datafusion.instances.setIamPolicy', 'gcp-persistence/gcp-data-fusion-persistence.md'),
    ('datafusion.namespaces.setIamPolicy', 'gcp-privilege-escalation/gcp-data-fusion-privesc.md'),
    ('datafusion.pipelineConnections.use', 'gcp-privilege-escalation/gcp-data-fusion-privesc.md'),
    ('datafusion.pipelines.create', 'gcp-privilege-escalation/gcp-data-fusion-privesc.md'),
    ('datafusion.pipelines.execute', 'gcp-privilege-escalation/gcp-data-fusion-privesc.md'),
    ('datafusion.secureKeys.getSecret', 'gcp-post-exploitation/gcp-data-fusion-post-exploitation.md'),
    ('datapipelines.pipelines.create', 'gcp-persistence/gcp-dataflow-persistence.md'),
    ('dataplex.assets.setIamPolicy', 'gcp-privilege-escalation/gcp-dataplex-privesc.md'),
    ('dataplex.lakes.setIamPolicy', 'gcp-privilege-escalation/gcp-dataplex-privesc.md'),
    ('dataplex.tasks.create', 'gcp-privilege-escalation/gcp-dataplex-privesc.md'),
    ('dataplex.zones.setIamPolicy', 'gcp-privilege-escalation/gcp-dataplex-privesc.md'),
    ('dataproc.batches.create', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('dataproc.clusters.create', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('dataproc.clusters.setIamPolicy', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('dataproc.sessionTemplates.create', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('dataproc.sessions.create', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('dataproc.workflowTemplates.create', 'gcp-privilege-escalation/gcp-dataproc-privesc.md'),
    ('datastore.databases.export', 'gcp-post-exploitation/gcp-firestore-post-exploitation.md'),
    ('datastore.userCreds.create', 'gcp-persistence/gcp-firestore-persistence.md'),
    ('datastore.userCreds.update', 'gcp-persistence/gcp-firestore-persistence.md'),
    ('datastream.connectionProfiles.create', 'gcp-persistence/gcp-datastream-persistence.md'),
    ('datastream.objects.startBackfillJob', 'gcp-post-exploitation/gcp-datastream-post-exploitation.md'),
    ('datastream.privateConnections.create', 'gcp-persistence/gcp-datastream-persistence.md'),
    ('datastream.routes.create', 'gcp-persistence/gcp-datastream-persistence.md'),
    ('datastream.streams.create', 'gcp-persistence/gcp-datastream-persistence.md'),
    ('datastream.streams.update', 'gcp-persistence/gcp-datastream-persistence.md'),
    ('deploymentmanager.deployments.create', 'gcp-privilege-escalation/gcp-deploymentmaneger-privesc.md'),
    ('deploymentmanager.deployments.setIamPolicy', 'gcp-privilege-escalation/gcp-deploymentmaneger-privesc.md'),
    ('deploymentmanager.deployments.update', 'gcp-privilege-escalation/gcp-deploymentmaneger-privesc.md'),
    ('deploymentmanager.manifests.get', 'gcp-post-exploitation/gcp-deployment-manager-post-exploitation.md'),
    ('developerconnect.gitRepositoryLinks.fetchReadToken', 'gcp-post-exploitation/gcp-developer-connect-post-exploitation.md'),
    ('developerconnect.gitRepositoryLinks.fetchReadWriteToken', 'gcp-post-exploitation/gcp-developer-connect-post-exploitation.md'),
    ('dialogflow.webhooks.update', 'gcp-post-exploitation/gcp-dialogflow-post-exploitation.md'),
    ('discoveryengine.collections.setIamPolicy', 'gcp-persistence/gcp-discovery-engine-persistence.md'),
    ('discoveryengine.dataStores.setIamPolicy', 'gcp-persistence/gcp-discovery-engine-persistence.md'),
    ('discoveryengine.engines.setIamPolicy', 'gcp-persistence/gcp-discovery-engine-persistence.md'),
    ('discoveryengine.identityMappingStores.importIdentityMappings', 'gcp-privilege-escalation/gcp-discovery-engine-privesc.md'),
    ('dlp.contentPolicies.update', 'gcp-post-exploitation/gcp-dlp-post-exploitation.md'),
    ('dlp.deidentifyTemplates.get', 'gcp-post-exploitation/gcp-dlp-post-exploitation.md'),
    ('dlp.deidentifyTemplates.update', 'gcp-post-exploitation/gcp-dlp-post-exploitation.md'),
    ('dlp.jobTriggers.create', 'gcp-persistence/gcp-dlp-persistence.md'),
    ('dlp.jobs.create', 'gcp-persistence/gcp-dlp-persistence.md'),
    ('dns.gkeClusters.bindDNSResponsePolicy', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.gkeClusters.bindPrivateDNSZone', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.managedZones.create', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.networks.bindDNSResponsePolicy', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.networks.bindPrivateDNSPolicy', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.networks.bindPrivateDNSZone', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.policies.create', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.policies.update', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.responsePolicies.create', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('dns.responsePolicyRules.create', 'gcp-post-exploitation/gcp-cloud-dns-post-exploitation.md'),
    ('documentai.datasets.getDocuments', 'gcp-post-exploitation/gcp-document-ai-post-exploitation.md'),
    ('documentai.datasets.listDocuments', 'gcp-post-exploitation/gcp-document-ai-post-exploitation.md'),
    ('documentai.processorVersions.create', 'gcp-post-exploitation/gcp-document-ai-post-exploitation.md'),
    ('domains.registrations.setIamPolicy', 'gcp-persistence/gcp-cloud-domains-persistence.md'),
    ('essentialcontacts.contacts.create', 'gcp-persistence/gcp-essential-contacts-persistence.md'),
    ('eventarc.enrollments.update', 'gcp-post-exploitation/gcp-eventarc-post-exploitation.md'),
    ('eventarc.pipelines.create', 'gcp-persistence/gcp-eventarc-persistence.md'),
    ('eventarc.triggers.create', 'gcp-persistence/gcp-cloud-run-persistence.md'),
    ('eventarc.triggers.update', 'gcp-post-exploitation/gcp-eventarc-post-exploitation.md'),
    ('file.backups.create', 'gcp-post-exploitation/gcp-filestore-post-exploitation.md'),
    ('file.backups.useReadOnly', 'gcp-post-exploitation/gcp-filestore-post-exploitation.md'),
    ('file.instances.create', 'gcp-post-exploitation/gcp-filestore-post-exploitation.md'),
    ('file.instances.update', 'gcp-persistence/gcp-filestore-persistence.md'),
    ('firebaseapphosting.backends.update', 'gcp-privilege-escalation/gcp-firebase-app-hosting-privesc.md'),
    ('firebaseapphosting.builds.create', 'gcp-privilege-escalation/gcp-firebase-app-hosting-privesc.md'),
    ('firebaseapphosting.rollouts.create', 'gcp-privilege-escalation/gcp-firebase-app-hosting-privesc.md'),
    ('firebaseauth.configs.update', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('firebaseauth.users.update', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('firebaserules.releases.create', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('firebaserules.releases.update', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('firebaserules.rulesets.create', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('gkebackup.backupPlans.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('gkebackup.backups.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('gkebackup.restorePlans.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('gkebackup.restores.create', 'gcp-post-exploitation/gcp-backup-and-dr-post-exploitation.md'),
    ('gkehub.features.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('gkehub.gateway.generateCredentials', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('gkehub.membershipfeatures.update', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('gkehub.memberships.setIamPolicy', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('gkehub.rbacrolebindings.create', 'gcp-privilege-escalation/gcp-container-privesc.md'),
    ('healthcare.consentStores.setIamPolicy', 'gcp-privilege-escalation/gcp-healthcare-privesc.md'),
    ('healthcare.datasets.create', 'gcp-post-exploitation/gcp-healthcare-post-exploitation.md'),
    ('healthcare.datasets.setIamPolicy', 'gcp-privilege-escalation/gcp-healthcare-privesc.md'),
    ('healthcare.dicomStores.export', 'gcp-post-exploitation/gcp-healthcare-post-exploitation.md'),
    ('healthcare.dicomStores.setIamPolicy', 'gcp-privilege-escalation/gcp-healthcare-privesc.md'),
    ('healthcare.fhirStores.export', 'gcp-post-exploitation/gcp-healthcare-post-exploitation.md'),
    ('healthcare.fhirStores.setIamPolicy', 'gcp-privilege-escalation/gcp-healthcare-privesc.md'),
    ('healthcare.fhirStores.update', 'gcp-persistence/gcp-healthcare-persistence.md'),
    ('healthcare.hl7V2Messages.create', 'gcp-post-exploitation/gcp-healthcare-post-exploitation.md'),
    ('healthcare.hl7V2Stores.export', 'gcp-post-exploitation/gcp-healthcare-post-exploitation.md'),
    ('healthcare.hl7V2Stores.setIamPolicy', 'gcp-privilege-escalation/gcp-healthcare-privesc.md'),
    ('hypercomputecluster.clusters.update', 'gcp-persistence/gcp-cluster-director-persistence.md'),
    ('iam.serviceAccounts.actAs', 'gcp-persistence/gcp-bigquery-persistence.md'),
    ('iam.serviceAccounts.undelete', 'gcp-persistence/gcp-iam-persistence.md'),
    ('iap.tunnelInstances.accessViaIAP', 'gcp-privilege-escalation/gcp-iap-privesc.md'),
    ('iap.tunnelInstances.setIamPolicy', 'gcp-persistence/gcp-iap-persistence.md'),
    ('iap.tunnelZones.setIamPolicy', 'gcp-persistence/gcp-iap-persistence.md'),
    ('iap.web.setIamPolicy', 'gcp-persistence/gcp-iap-persistence.md'),
    ('iap.web.updateSettings', 'gcp-privilege-escalation/gcp-iap-privesc.md'),
    ('iap.webServiceVersions.setIamPolicy', 'gcp-persistence/gcp-iap-persistence.md'),
    ('iap.webServices.setIamPolicy', 'gcp-persistence/gcp-iap-persistence.md'),
    ('identitytoolkit.tenants.setIamPolicy', 'gcp-privilege-escalation/gcp-firebase-privesc.md'),
    ('integrations.authConfigs.get', 'gcp-to-workspace-pivoting/gcp-application-integration-privesc.md'),
    ('livestream.channels.get', 'gcp-post-exploitation/gcp-live-stream-post-exploitation.md'),
    ('livestream.channels.start', 'gcp-post-exploitation/gcp-live-stream-post-exploitation.md'),
    ('livestream.events.create', 'gcp-post-exploitation/gcp-live-stream-post-exploitation.md'),
    ('livestream.inputs.create', 'gcp-post-exploitation/gcp-live-stream-post-exploitation.md'),
    ('logging.links.create', 'gcp-post-exploitation/gcp-logging-post-exploitation.md'),
    ('logging.notificationRules.create', 'gcp-persistence/gcp-monitoring-persistence.md'),
    ('logging.sinks.create', 'gcp-persistence/gcp-logging-persistence.md'),
    ('logging.sinks.update', 'gcp-persistence/gcp-logging-persistence.md'),
    ('logging.views.create', 'gcp-post-exploitation/gcp-logging-post-exploitation.md'),
    ('logging.views.setIamPolicy', 'gcp-post-exploitation/gcp-logging-post-exploitation.md'),
    ('managedflink.deployments.create', 'gcp-persistence/gcp-managed-flink-persistence.md'),
    ('managedflink.jobs.create', 'gcp-persistence/gcp-managed-flink-persistence.md'),
    ('managedidentities.domains.resetpassword', 'gcp-post-exploitation/gcp-managed-microsoft-ad-post-exploitation.md'),
    ('managedkafka.acls.create', 'gcp-persistence/gcp-managed-kafka-persistence.md'),
    ('mcp.tools.call', 'gcp-persistence/gcp-cx-agent-studio-persistence.md'),
    ('metastore.services.setIamPolicy', 'gcp-persistence/gcp-dataproc-metastore-persistence.md'),
    ('modelarmor.floorSettings.update', 'gcp-post-exploitation/gcp-model-armor-post-exploitation.md'),
    ('modelarmor.templates.update', 'gcp-post-exploitation/gcp-model-armor-post-exploitation.md'),
    ('monitoring.alertPolicies.create', 'gcp-persistence/gcp-monitoring-persistence.md'),
    ('monitoring.notificationChannels.create', 'gcp-persistence/gcp-monitoring-persistence.md'),
    ('monitoring.notificationChannels.update', 'gcp-persistence/gcp-monitoring-persistence.md'),
    ('monitoring.uptimeCheckConfigs.create', 'gcp-persistence/gcp-monitoring-persistence.md'),
    ('netapp.backups.useReadOnly', 'gcp-post-exploitation/gcp-netapp-volumes-post-exploitation.md'),
    ('netapp.volumes.create', 'gcp-post-exploitation/gcp-netapp-volumes-post-exploitation.md'),
    ('networkconnectivity.groups.setIamPolicy', 'gcp-privilege-escalation/gcp-network-connectivity-center-privesc.md'),
    ('networkconnectivity.hubs.create', 'gcp-post-exploitation/gcp-vpc-network-post-exploitation.md'),
    ('networkconnectivity.hubs.setIamPolicy', 'gcp-privilege-escalation/gcp-network-connectivity-center-privesc.md'),
    ('networkconnectivity.hubs.use', 'gcp-post-exploitation/gcp-vpc-network-post-exploitation.md'),
    ('networkconnectivity.policyBasedRoutes.create', 'gcp-post-exploitation/gcp-vpc-network-post-exploitation.md'),
    ('networkconnectivity.spokes.create', 'gcp-post-exploitation/gcp-vpc-network-post-exploitation.md'),
    ('networksecurity.addressGroups.setIamPolicy', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.addressGroups.update', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.authorizationPolicies.setIamPolicy', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.authorizationPolicies.update', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.authzPolicies.create', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.authzPolicies.setIamPolicy', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.authzPolicies.update', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.clientTlsPolicies.setIamPolicy', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.interceptDeploymentGroups.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.interceptDeployments.create', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.interceptEndpointGroupAssociations.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.interceptEndpointGroups.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.interceptEndpointGroups.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.mirroringDeploymentGroups.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.mirroringEndpointGroupAssociations.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.mirroringEndpointGroups.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.mirroringEndpointGroups.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.securityProfileGroups.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.securityProfileGroups.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.securityProfiles.create', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.securityProfiles.update', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.securityProfiles.use', 'gcp-post-exploitation/gcp-ids-post-exploitation.md'),
    ('networksecurity.serverTlsPolicies.setIamPolicy', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networksecurity.serverTlsPolicies.use', 'gcp-post-exploitation/gcp-certificate-manager-post-exploitation.md'),
    ('networkservices.authzExtensions.create', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('networkservices.authzExtensions.use', 'gcp-privilege-escalation/gcp-networksecurity-privesc.md'),
    ('networkservices.googleTagGatewayPolicies.create', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('networkservices.lbTrafficExtensions.create', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('networkservices.meshes.use', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('networkservices.wasmPlugins.create', 'gcp-privilege-escalation/gcp-networkservices-privesc.md'),
    ('notebooks.instances.create', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('notebooks.instances.reset', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('notebooks.instances.setIamPolicy', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('notebooks.instances.update', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('notebooks.instances.use', 'gcp-privilege-escalation/gcp-vertex-ai-privesc.md'),
    ('observability.links.create', 'gcp-post-exploitation/gcp-observability-post-exploitation.md'),
    ('observability.views.access', 'gcp-post-exploitation/gcp-observability-post-exploitation.md'),
    ('oracledatabase.autonomousDatabases.generateWallet', 'gcp-post-exploitation/gcp-oracle-database-post-exploitation.md'),
    ('orgpolicy.customConstraints.create', 'gcp-privilege-escalation/gcp-orgpolicy-privesc.md'),
    ('orgpolicy.customConstraints.update', 'gcp-privilege-escalation/gcp-orgpolicy-privesc.md'),
    ('orgpolicy.policies.create', 'gcp-privilege-escalation/gcp-orgpolicy-privesc.md'),
    ('orgpolicy.policies.delete', 'gcp-privilege-escalation/gcp-orgpolicy-privesc.md'),
    ('orgpolicy.policies.update', 'gcp-privilege-escalation/gcp-orgpolicy-privesc.md'),
    ('osconfig.guestPolicies.create', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('osconfig.guestPolicies.update', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('osconfig.osPolicyAssignments.create', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('osconfig.osPolicyAssignments.update', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('osconfig.patchDeployments.create', 'gcp-persistence/gcp-compute-persistence.md'),
    ('osconfig.patchDeployments.update', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('osconfig.policyOrchestrators.create', 'gcp-privilege-escalation/gcp-osconfig-privesc.md'),
    ('privateca.caPools.setIamPolicy', 'gcp-privilege-escalation/gcp-certificate-authority-service-privesc.md'),
    ('privateca.caPools.update', 'gcp-privilege-escalation/gcp-certificate-authority-service-privesc.md'),
    ('privateca.certificateAuthorities.create', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('privateca.certificateAuthorities.update', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('privateca.certificateTemplates.update', 'gcp-privilege-escalation/gcp-certificate-authority-service-privesc.md'),
    ('privateca.certificateTemplates.use', 'gcp-privilege-escalation/gcp-certificate-authority-service-privesc.md'),
    ('privateca.certificates.create', 'gcp-persistence/gcp-certificate-authority-service-persistence.md'),
    ('privateca.certificates.createForSelf', 'gcp-privilege-escalation/gcp-certificate-authority-service-privesc.md'),
    ('pubsub.subscriptions.create', 'gcp-persistence/gcp-cloud-run-persistence.md'),
    ('pubsub.subscriptions.setIamPolicy', 'gcp-persistence/gcp-pub-sub-persistence.md'),
    ('pubsub.subscriptions.update', 'gcp-post-exploitation/gcp-pub-sub-post-exploitation.md'),
    ('pubsub.topics.attachSubscription', 'gcp-post-exploitation/gcp-pub-sub-post-exploitation.md'),
    ('pubsub.topics.setIamPolicy', 'gcp-persistence/gcp-healthcare-persistence.md'),
    ('recaptchaenterprise.firewallpolicies.create', 'gcp-post-exploitation/gcp-recaptcha-enterprise-post-exploitation.md'),
    ('recaptchaenterprise.firewallpolicies.update', 'gcp-post-exploitation/gcp-recaptcha-enterprise-post-exploitation.md'),
    ('recaptchaenterprise.keys.retrievelegacysecretkey', 'gcp-post-exploitation/gcp-recaptcha-enterprise-post-exploitation.md'),
    ('recaptchaenterprise.keys.update', 'gcp-post-exploitation/gcp-recaptcha-enterprise-post-exploitation.md'),
    ('recaptchaenterprise.policies.update', 'gcp-post-exploitation/gcp-recaptcha-enterprise-post-exploitation.md'),
    ('redis.clusters.connect', 'gcp-post-exploitation/gcp-memorystore-post-exploitation.md'),
    ('redis.instances.export', 'gcp-post-exploitation/gcp-memorystore-post-exploitation.md'),
    ('resourcemanager.folders.move', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.hierarchyNodes.createTagBinding', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.projects.deletePolicyBinding', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.projects.move', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.projects.update', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.projects.updatePolicyBinding', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.tagKeys.setIamPolicy', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.tagValueBindings.create', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('resourcemanager.tagValues.setIamPolicy', 'gcp-privilege-escalation/gcp-resourcemanager-privesc.md'),
    ('run.jobs.create', 'gcp-privilege-escalation/gcp-run-privesc.md'),
    ('run.jobs.setIamPolicy', 'gcp-privilege-escalation/gcp-run-privesc.md'),
    ('run.jobs.update', 'gcp-privilege-escalation/gcp-run-privesc.md'),
    ('run.locations.exportImage', 'gcp-post-exploitation/gcp-cloud-run-post-exploitation.md'),
    ('run.services.create', 'gcp-post-exploitation/gcp-cloud-run-post-exploitation.md'),
    ('run.services.setIamPolicy', 'gcp-persistence/gcp-cloud-run-persistence.md'),
    ('run.services.update', 'gcp-persistence/gcp-cloud-run-persistence.md'),
    ('run.workerpools.create', 'gcp-privilege-escalation/gcp-run-privesc.md'),
    ('run.workerpools.update', 'gcp-privilege-escalation/gcp-run-privesc.md'),
    ('runtimeconfig.configs.setIamPolicy', 'gcp-privilege-escalation/gcp-runtimeconfig-privesc.md'),
    ('runtimeconfig.variables.get', 'gcp-post-exploitation/gcp-runtimeconfig-post-exploitation.md'),
    ('saasservicemgmt.releases.create', 'gcp-privilege-escalation/gcp-app-lifecycle-manager-privesc.md'),
    ('secretmanager.secrets.enableManagedRotation', 'gcp-privilege-escalation/gcp-secretmanager-privesc.md'),
    ('secretmanager.secrets.setIamPolicy', 'gcp-privilege-escalation/gcp-secretmanager-privesc.md'),
    ('secretmanager.secrets.update', 'gcp-persistence/gcp-secret-manager-persistence.md'),
    ('secretmanager.versions.access', 'gcp-post-exploitation/gcp-cloud-sql-post-exploitation.md'),
    ('secretmanager.versions.add', 'gcp-post-exploitation/gcp-secretmanager-post-exploitation.md'),
    ('securesourcemanager.branchRules.create', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securesourcemanager.hooks.create', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securesourcemanager.instances.setIamPolicy', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securesourcemanager.repositories.approvePullRequests', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securesourcemanager.repositories.fetch', 'gcp-post-exploitation/gcp-secure-source-manager-post-exploitation.md'),
    ('securesourcemanager.repositories.readPullRequests', 'gcp-post-exploitation/gcp-secure-source-manager-post-exploitation.md'),
    ('securesourcemanager.repositories.setIamPolicy', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securesourcemanager.sshkeys.createAny', 'gcp-privilege-escalation/gcp-secure-source-manager-privesc.md'),
    ('securitycenter.sources.setIamPolicy', 'gcp-privilege-escalation/gcp-security-command-center-privesc.md'),
    ('servicedirectory.endpoints.create', 'gcp-post-exploitation/gcp-service-directory-post-exploitation.md'),
    ('servicedirectory.endpoints.update', 'gcp-post-exploitation/gcp-service-directory-post-exploitation.md'),
    ('servicedirectory.namespaces.setIamPolicy', 'gcp-persistence/gcp-service-directory-persistence.md'),
    ('servicedirectory.networks.attach', 'gcp-post-exploitation/gcp-service-directory-post-exploitation.md'),
    ('servicedirectory.services.setIamPolicy', 'gcp-persistence/gcp-service-directory-persistence.md'),
    ('servicemanagement.services.setIamPolicy', 'gcp-privilege-escalation/gcp-service-management-privesc.md'),
    ('servicemanagement.services.update', 'gcp-privilege-escalation/gcp-service-management-privesc.md'),
    ('serviceusage.services.use', 'gcp-persistence/gcp-alloydb-persistence.md'),
    ('source.repos.setIamPolicy', 'gcp-privilege-escalation/gcp-sourcerepos-privesc.md'),
    ('spanner.backups.create', 'gcp-privilege-escalation/gcp-spanner-privesc.md'),
    ('spanner.backups.restoreDatabase', 'gcp-privilege-escalation/gcp-spanner-privesc.md'),
    ('spanner.databases.create', 'gcp-privilege-escalation/gcp-spanner-privesc.md'),
    ('spanner.databases.createBackup', 'gcp-privilege-escalation/gcp-spanner-privesc.md'),
    ('spanner.databases.setIamPolicy', 'gcp-persistence/gcp-spanner-persistence.md'),
    ('spanner.databases.updateDdl', 'gcp-persistence/gcp-spanner-persistence.md'),
    ('spanner.instances.setIamPolicy', 'gcp-persistence/gcp-spanner-persistence.md'),
    ('storage.buckets.create', 'gcp-post-exploitation/gcp-pub-sub-post-exploitation.md'),
    ('storage.buckets.delete', 'gcp-post-exploitation/gcp-pub-sub-post-exploitation.md'),
    ('storage.buckets.restore', 'gcp-post-exploitation/gcp-storage-post-exploitation.md'),
    ('storage.buckets.setIamPolicy', 'gcp-persistence/gcp-logging-persistence.md'),
    ('storage.buckets.update', 'gcp-persistence/gcp-cloud-scheduler-persistence.md'),
    ('storage.managedFolders.setIamPolicy', 'gcp-privilege-escalation/gcp-storage-privesc.md'),
    ('storagetransfer.jobs.create', 'gcp-post-exploitation/gcp-storage-transfer-post-exploitation.md'),
    ('storagetransfer.jobs.run', 'gcp-post-exploitation/gcp-storage-transfer-post-exploitation.md'),
    ('storagetransfer.jobs.update', 'gcp-post-exploitation/gcp-storage-transfer-post-exploitation.md'),
    ('vmmigration.imageImports.create', 'gcp-post-exploitation/gcp-vm-migration-post-exploitation.md'),
    ('vmmigration.migratingVms.create', 'gcp-post-exploitation/gcp-vm-migration-post-exploitation.md'),
    ('vmwareengine.privateClouds.setIamPolicy', 'gcp-privilege-escalation/gcp-vmwareengine-gcve-privesc.md'),
    ('vpcaccess.connectors.create', 'gcp-post-exploitation/gcp-cloud-run-post-exploitation.md'),
    ('workflows.workflows.update', 'gcp-persistence/gcp-workflows-persistence.md'),
    ('workstations.workstationConfigs.create', 'gcp-privilege-escalation/gcp-cloud-workstations-privesc.md'),
    ('workstations.workstations.setIamPolicy', 'gcp-privilege-escalation/gcp-cloud-workstations-privesc.md'),
)
